### ISSUE TITLE
Feature request: Function to assert every element of an array is equal to a particular value

### ISSUE THREAD

**Issue by JonathonReinhart** [ThrowTheSwitch/Unity#100]
Unity needs a `TEST_ASSERT` to verify that every element of an array is equal to a single value.

Simple example: I want to test that my `memset` function properly sets a range of bytes equal to a particular value.

`TEST_ASSERT_EQUAL_MEMORY` compares two blocks of memory, but I want to compare one block of memory to a single value.

You could call `TEST_ASSERT_EQUAL` in a loop over each byte (or element of the actual array) but this doesn't provide any indication as to which element failed.

Currently, to emulate this, one needs to construct an `expected` array, and then use `TEST_ASSERT_EQUAL_MEMORY` to verify that they are equal.

_(I already submitted this via email, but wanted to track it on GitHub, as I may get time to implement this.)_

**Comment by mvandervoord** [comment]
While this has been a good idea for over two years, I finally added it to the main codebase today. (see 550d58b). My humblest apologies on the long road to get here.

**Comment by JonathonReinhart** [comment]
Awesome, thanks @mvandervoord!
