### ISSUE TITLE
Failing tests miss EOL in output

### ISSUE THREAD

**Issue by tarikku** [ThrowTheSwitch/Unity#101]
It seems that failing tests (at least ones due to failing asserts) miss an EOL at the end of the printed line.

This is the output from a sample project, in which the output belonging to the next test is just appended to the output of the previous test case that failed:
TEST(BowlingGame, TestGutter)test/bowlinggame/bowlinggameTest.c:22:TEST(BowlingGame, TestGutter):FAIL: Expected 1 Was 0TEST(BowlingGame, TestAllOnes) PASS

**Comment by emidttun** [comment]
Do you observe this for unity or unity_fixture? I have the observed the same for unity_fixture when tests fail or are ignored. Things looks much better when using the '-v' option.

**Comment by mvandervoord** [comment]
I believe this issue in fixtures is now fixed. Please reopen if that doesn't seem true to you.
