### ISSUE TITLE
unity_fixure output is different from normal unity output

### ISSUE THREAD

**Issue by emidttun** [ThrowTheSwitch/Unity#107]
Since the unity_fixture format is different from unity it will not work with parseOutput.rb for generating XML. Is this something that is planned to be fixed? (Haven't seen a lot of activity in the fixture directory.)

**Comment by mvandervoord** [comment]
Thanks for the good question. I might not have the answer you are hoping for: This is not planned to be "fixed". Two reasons:
(1) as you noticed, we rarely do updates to the fixture option. It's not the supported way to use Unity and was submitted by a third party to make Unity act like CppUTest. 
(2) The output format of fixtures is made to act like xUnit test frameworks, which was not a goal of Unity itself. They therefore have different goals and won't be joining forces.
