### ISSUE TITLE
Backslash in file path should be escaped

### ISSUE THREAD

**Issue by emileb** [ThrowTheSwitch/Unity#127]
When printing out the test file name, path separators should be double slash, otherwise a tab (or other codes) appears in this example:

 UnityBegin("my_tests\test.c");

Hacked generate_test_runner.rb with:

filename_slash = filename.dup;
output.puts("  UnityBegin(\"#{filename_slash.gsub!("\\", "\\\\\\")}\");")

**Comment by mvandervoord** [comment]
Thanks! I'll fix this when I get a chance!
