### ISSUE TITLE
How are the docs generated?

### ISSUE THREAD

**Issue by w1res** [ThrowTheSwitch/Unity#129]
How are the docs generated (i.e., the pdf and odt)? I have some grammatical/typos to fix in them but don't know what the source for them is, or how to build them.

**Comment by mvandervoord** [comment]
The odt file is edited directly in open office (or libre office or star office or whatever compatible program you want to use). Then we export a new pdf from that. The text file is unfortunately manually edited each time.

Thanks for your offer to help!
