### ISSUE TITLE
compilation with fixture

### ISSUE THREAD

**Issue by zen0x90** [ThrowTheSwitch/Unity#138]
hi,

When compiling unity (fixture) with my tests I got a lot of errors related to multiple redefinition (macros TEST, ...).

Please see below my project tree :
```
tests
|-- makefile
|-- test
|   |-- test.c
|   `-- main.c
`-- unity
    |-- inc
    |   |-- unity.h
    |   |-- unity_fixture.h
    |   |-- unity_fixture_internals.h
    |   |-- unity_fixture_malloc_overrides.h
    |   `-- unity_internals.h
    `-- src
        |-- unity.c
        `-- unity_fixture.c
```
My test.c file is a standard empty test but it is not important as my issue come from the compilation. However, I include only test_internal.h in test.c and main.c.

Please see below my Makefile:
```makefile
# ==========================================
#   Unity Project - A Test Framework for C
#   Copyright (c) 2007 Mike Karlesky, Mark VanderVoord, Greg Williams
#   [Released under MIT License. Please refer to license.txt for details]
# ==========================================

#We try to detect the OS we are running on, and adjust commands as needed
ifeq ($(OSTYPE),cygwin)
	CLEANUP = rm -f
	MKDIR = mkdir -p
	TARGET_EXTENSION=.out
elseifeq ($(OSTYPE),msys)
	CLEANUP = rm -f
	MKDIR = mkdir -p
	TARGET_EXTENSION=.exe
elseifeq ($(OS),Windows_NT)
	CLEANUP = del /F /Q
	MKDIR = mkdir
	TARGET_EXTENSION=.exe
else
	CLEANUP = rm -f
	MKDIR = mkdir -p
	TARGET_EXTENSION=.out
endif

UNITY_ROOT=$(TOP)/test/unity
C_COMPILER=gcc
SYMBOLS=-DTEST

CFLAGS=-std=c99
CFLAGS += -Wall
CFLAGS += -Wextra
CFLAGS += -Werror 
CFLAGS += -Wpointer-arith
CFLAGS += -Wcast-align
CFLAGS += -Wwrite-strings
CFLAGS += -Wswitch-default
CFLAGS += -Wunreachable-code
CFLAGS += -Winit-self
CFLAGS += -Wmissing-field-initializers
CFLAGS += -Wno-unknown-pragmas
CFLAGS += -Wstrict-prototypes
CFLAGS += -Wundef
CFLAGS += -Wold-style-definition
CFLAGS += -D _GNU_SOURCE

TARGET := test$(TARGET_EXTENSION)

SRC_FWK  :=  $(UNITY_ROOT)/src
INC_FWK  := -I$(UNITY_ROOT)/inc
INCS     := $(INC_FWK)

SRC_DIR  := test
SRCS     := $(SRC_FWK) $(wildcard $(SRC_DIR)/*.c)

all: clean default

default:
	$(C_COMPILER) $(CFLAGS) $(INCS) $(SYMBOLS) $(SRCS) -o $(TARGET)
	./$(TARGET)
clean:
	$(CLEANUP) *~
	$(CLEANUP) \#*\#
	$(CLEANUP) $(SRC_DIR)/*~
	$(CLEANUP) $(SRC_DIR)/\#*\#
	$(CLEANUP) $(TARGET)
```

$ make
```
In file included from test/test.c:1:0:
[...]/tests/unity/inc/unity_fixture.h:29:0: error: "TEST" redefined [-Werror]
 #define TEST(group, name) \
 ^
<command-line>:0:0: note: this is the location of the previous definition
test/test.c:7:1: error: return type defaults to 'int' [-Werror]
 TEST_TEARDOWN(str) {}
[...]
```

I think this error come from unity_internal.h which include unity.h. But all examples on the net shows approximatively the same structure and compilation line.

Do you know how to fix it ?

Cheers

**Comment by mvandervoord** [comment]
Your source file for the unit (main.c in your case?) should not know
anything about testing at all... therefore don't include any of the unity
files there. Your test file that goes with that source module should
include unity.h only. unity_internals will automatically get included from
there.

This article might be a good starting point:

http://www.throwtheswitch.org/build/build-unity

Also, if you really are going to test your main function, this might also
be helpful:

http://vandervoord.net/blog/2015/5/19/unit-test-how-main-

I hope this helps. If you have other questions, please ask!

Mark

**Comment by zen0x90** [comment]
Hi Mark,

I'm sorry I should put the content of main.c and test.c:

- test.c
```C
#include <unity_fixture.h>

TEST_GROUP(foo);

TEST_SETUP(foo)    {}
TEST_TEARDOWN(foo) {}

TEST(foo, test)
{
  TEST_ASSERT_EQUAL_INT(0, 0);
}

TEST_GROUP_RUNNER(foo)
{
  RUN_TEST_CASE(foo, test);
}
```

- main.c 
```C
#include <unity_fixture.h>

static void run_tests(void)
{
  RUN_TEST_GROUP(foo);
}

int main(int ac, char **av)
{
  return UnityMain(ac, av, run_tests);
}
```

Cheers,

**Comment by mjago** [comment]
Hi 
TEST is already defined (see your makefile above SYMBOLS=-DTEST). Try renaming TEST(group, test) to TEST_SOMETHING(group, test).

Martyn

**Comment by mvandervoord** [comment]
Martyn's advice is good and likely the problem you ran into. Also, I
realize I did a really poor job of reading your original email and I
apologize for that. I see now that you are using fixture, which means you
will want to include "unity_fixture.h" instead of "unity.h" in your tests
and runner files (which in this case was main.c for you?)

Mark

**Comment by zen0x90** [comment]
Hi,

Thanks you for your reply.

@Mark

True. I want to use unity_fixture.h and this is why I created a main.c.

@Martyn

In fact, I stole the makefile from example in Unity git. I changed it a little bit but I kept the same basis. I don't the utility of SYMBOLS variable but if I change CHANGE TEST to TEST_SOMETHING I need to declare it somewhere but how ?

Cheers

**Comment by mjago** [comment]
Hi

I'm not that familiar with fixtures so didn't know about the definition of TEST(x, y) in there. In that case remove the SYMBOLS=-DTEST line in your makefile. All it does is declare TEST within the test build which can be used by the pre-processor to determine whether it is a test build or not (and is possibly used by some automated test runners). I don't think Unity uses it.

Martyn

**Comment by zen0x90** [comment]
H guys,

Thank you so much everything is working fine now. So simple...:(

Cheers
