### ISSUE TITLE
Segfault on simple test

### ISSUE THREAD

**Issue by sontek** [ThrowTheSwitch/Unity#145]
hello_test.c:

```c
#include "unity.h"

int main(void) {
  TEST_ASSERT_EQUAL(0, 1);
}
```

compile:

```bash
gcc hello_test.c unity.c
```

result:

```bash
./a.out 
Segmentation fault (core dumped)
```

**Comment by mvandervoord** [comment]
:) You've simplified your test too much. You haven't left anywhere for your failures to report. A minimal test would look something like this:

```C
#include "unity.h"

int main(void) {
    UNITY_BEGIN();
    if (TEST_PROTECT()) {
        TEST_ASSERT_EQUAL(0,1);
   }
   return UNITY_END();
}
```

Really, though, it's good practice to make a function per test and use the RUN_TEST macro:

```C
#include "unity.h"

void test_BlahBlahBlah(void) {
    TEST_ASSERT_EQUAL(0,1);
}

int main(void) {
    UNITY_BEGIN();
    RUN_TEST(test_BlahBlahBlah);
   return UNITY_END();
}
```

If you do either of those methods, you shouldn't see the segfault. If you still do, we should start talking about what version of gcc you are using, on what platform, for what target, etc.

I hope this helps!

Mark
