### ISSUE TITLE
Fail and Ignore macro has a superfluous semi-colon

### ISSUE THREAD

**Issue by martinn16** [ThrowTheSwitch/Unity#147]
At the end of the UNITY_TEST_FAIL and UNITY_TEST_IGNORE macros are superfluous semi-colons, these become indented onto the next line when auto-formatting.

e.g.
TEST_IGNORE()
;

This is fixed by removing the semi-colons at the end of lines 596 & 597 of unity_internals.h, making them consistent with the other macros.

I tried to create a pull request for this but authentication failed.

**Comment by mvandervoord** [comment]
Thanks. I'll have it patched up in a jiffy.

**Comment by martinn16** [comment]
No problem :)
