### ISSUE TITLE
Test runner generator creates unnecessary output

### ISSUE THREAD

**Issue by pmendham** [ThrowTheSwitch/Unity#157]
A commit on 18th August 2015 (98e8590fce46ecc8aaab3c7b5efe52c345e0aee4) included a change to generate_test_runner.rb which caused it to spit a bunch of output out at the end of execution (see line 372). Is this necessary? We don't use Ceedling and this output fills the user's screen with unhelpful output. Would it be possible to revert this back to not doing the puts?

**Comment by mvandervoord** [comment]
Fixed a long time ago. I forgot to close this. Sorry about that.
