### ISSUE TITLE
Fail to build unity_fixture_Test.c because of Spy macros

### ISSUE THREAD

**Issue by aburks** [ThrowTheSwitch/Unity#168]
I'm unable to build unity_fixture_Test.c on latest master @ f31667ad18cf03c68c1d7a4dadb1debe4c1b1ca9 because of the following error:

`unity_fixture_Test.c:319:50: error: pasting "VAL_FUNC_" and "(" does not give a valid preprocessing token`

Remove the parens from `UNITY_OUTPUT_CHAR` solves this issue. It could be caused by my embedded development environment and how `putchar` is implemented.

**Comment by aburks** [comment]
To elaborate on this: we are using an embedded system that may be defining `putchar` as a macro rather than a declared function, so when the Spy selection macro runs into `putchar()` we get this compiler issue.

**Comment by jsalling** [comment]
I'd like to fix this, if you can give me some more info. I'm having a hard time reproducing just this error. My suspicion is that using the output Spy will solve your problem and get the tests to run. 
Compile with `-D UNITY_OUTPUT_CHAR=UnityOutputCharSpy_OutputChar`.

If `putchar` is defined as `(_some_putchar)` wrapped in parens, you'd get this error, but this seems unlikely for a standard library. Anyway,
Which compiler, version, and target are you using?
How are you defining `UNITY_OUTPUT_CHAR`, if at all?
Can you find the definition of `putchar` in your compiler header files?

**Comment by jsalling** [comment]
@mvandervoord Can you add me as assigned to this issue or close it? I pushed a fix.

I looked into this using the bare-metal ARM gcc cross compiler, `arm-none-eabi-gcc` version 5.2. User @aburks mentioned it was an issue on an embedded system.
First, compiling with `-D UNITY_OUTPUT_CHAR=UnityOutputCharSpy_OutputChar` does indeed work. Still, I _**was**_ able to reproduce the issue when not using the Spy. The cross compiler sets `putchar()` to expand to `(--(_put …` which breaks the Spy detection as reported.

Removing the function-like macro syntax prevents the Spy detection from working with defines like:
`#define UNITY_OUTPUT_CHAR(a) OutputChar(a)`
Continue to use this style, without parameters, for the Spy on testing builds:
`#define UNITY_OUTPUT_CHAR OutputChar` or as a compiler flag like above.

**Comment by aburks** [comment]
Thank you, @jsalling! Apologies for the dearth of information but you deftly figured it out. Thanks again!
