### ISSUE TITLE
Version bumps should be git-tagged

### ISSUE THREAD

**Issue by xor-gate** [ThrowTheSwitch/Unity#184]
It would be nice if (new) version bumps could be tagged with `git tag`. When mirroring Unity in a company git repo, the tags could be used to pin the dependency on. Now this is only done in the "magic" release folder under the file `release/version.info`.

**Comment by rikvdh** [comment]
:+1: for tagged releases!

**Comment by rikvdh** [comment]
@mvandervoord Is it possible to add git tags for releases any time soon?

**Comment by xor-gate** [comment]
It is specially usefull when people are mirroring unity, and setting commit pointers to version tags. Instead of commit where `release/version.info` is bumped. The commits where `release/version.info` is touched they could be tagged.

**Comment by mvandervoord** [comment]
Do either of you know if this is a manual process each time? It seems like this requires me to decide when we have reached a new "version", update the version.info, and then to manually tag the release on github. I'm okay with doing that, if necessary, it just seems like something that wants some automation to make it more streamlined. :)

**Comment by xor-gate** [comment]
You can automate this, after updating version.info then git tag with the same version number and then push the tag.

**Comment by mvandervoord** [comment]
Awesome. sold!  ;)

**Comment by xor-gate** [comment]
Just that easy 💃
