### ISSUE TITLE
stylize_as_junit.rb cannot cope with result files with 0 tests

### ISSUE THREAD

**Issue by cyclingengineer** [ThrowTheSwitch/Unity#195]
I get an error reported if I run the stylize_as_junit.rb script on a set of test results that have some results files that have 0 tests in them, but the script does seem to output the xml file (though I haven't checked the validity of it's contents).

Example results file:

```
-----------------------
0 Tests 0 Failures 0 Ignored 
OK
```

Gives this error from the script:

```
ERROR:
undefined method `+' for nil:NilClass
Usage: unity_to_junit.rb [options]

Specific options:
    -r, --results <dir>              Look for Unity Results files here.
    -p, --root_path <path>           Prepend this path to files in results.
    -o, --output <filename>          XML file to generate.

Common options:
    -h, --help                       Show this message
        --version                    Show version
```

Thanks,
Paul

**Comment by mvandervoord** [comment]
Paul:

Thanks for bringing this to our attention. Can you grab version 7c3d829 and let me know if that fixes the issue for you?

Thanks!
