### ISSUE TITLE
Example_1 Doesn't Work Because Unity.c has one function that doesn't conform to C89

### ISSUE THREAD

**Issue by ander454** [ThrowTheSwitch/Unity#208]
master: f276c79f9b5a66703bd20618e8a0bab699bfe738

Solution is to replace "//" comments with "/*" in function near line 1453 in unity.c.

Or maybe I'm doing something wrong because I'm a noob?

Details...

$ mingw32-make
rm -f
ruby ../../auto/generate_test_runner.rb test/TestProductionCode.c  test/test_runners/TestProductionCode_Runner.c
ruby ../../auto/generate_test_runner.rb test/TestProductionCode2.c test/test_runners/TestProductionCode2_Runner.c
gcc -std=c89 -Wall -Wextra -Werror  -Wpointer-arith -Wcast-align -Wwrite-strings -Wswitch-default -Wunreachable-code -Winit-self -Wmissing-field-initializers -Wno-unknown-pragmas -Wstrict-prototypes -Wundef -Wold-style-definition -Isrc -I../../src -IC:/MinGW/include -DTEST ../../src/unity.c src/ProductionCode.c  test/TestProductionCode.c  test/test_runners/TestProductionCode_Runner.c -o test1.out
../../src/unity.c:1453:16: error: missing terminating ' character [-Werror]
     //we couldn't find a match for any substrings
                ^
cc1.exe: all warnings being treated as errors
makefile:59: recipe for target 'default' failed
mingw32-make: *** [default] Error 1

**Comment by Letme** [comment]
Warning tells you it is about the `'` character that is causing the problem not the comment style. And why is `//` not C89? It more seems like there is something else going on there not on spot it is reported.

Did `/*` comment fix the issue? It might be something mingw has problems with...

**Comment by jsalling** [comment]
Good find @ander454.
Confirmed this issue. The gcc C Preprocessor expects to find matched `" "` and `' '`, even inside code that is removed with `#ifdef`. The switch to C89 style comments should do the trick.

**Comment by mvandervoord** [comment]
Thanks. Fixed in daad2bc
