### ISSUE TITLE
Bullseye/Clover - Unknown option error while excluding files from coverage 

### ISSUE THREAD

**Issue by hemaggopal** [ThrowTheSwitch/Unity#230]
Existing code invokes cov01 commands through ant. Now I have to exclude few files. covselect is throwing the following error. Could someone provide pointers on this?

`error: unknown option "--add \!**/filename.extn1.*/" 
`
```
//Trying to exclude files with name "filename.extn1.*" in any folder
<exec failonerror="false" failifexecutionfails="false" executable="covselect">
    <arg value="--add  \!**/filename.extn1.*/"/>
</exec>

//Enabling the coverage
<exec failonerror="false" failifexecutionfails="false" executable="cov01">
    <arg value="-1" />
</exec>

//Building the files
....

//Disabling the coverage
<exec failonerror="false" failifexecutionfails="false" executable="cov01">
    <arg value="-0" />
</exec>
```

**Comment by mvandervoord** [comment]
I'd love to be able to help with this, but I don't really know this tool well enough. As it's not really related to Unity (other than you happen to be using them together) I am going to close this issue. My apologies.
