### ISSUE TITLE
Drop support for end of life Rubies

### ISSUE THREAD

**Issue by mjago** [ThrowTheSwitch/Unity#234]
I notice that the ruby test runner still has support for pre 1.9.0 Ruby versions 😮 .

Currently only Ruby versions 2.1 and higher are supported by Ruby (including security fixes) and 2.4.0 will be released at the end of the month.

I think it would make sense to actively avoid support for out-of-date Rubies so all can benefit from the improved performance of an up-to-date ruby version (YARV for instance), and the test runner can be optimised to suit.

I can provide a pull-request if it is agreed.

**Comment by mvandervoord** [comment]
Ha, yes. I think it is time. :)

**Comment by mvandervoord** [comment]
Fixed in commit c3658a0
