### ISSUE TITLE
Potential buffer overrun in unity.c line 160

### ISSUE THREAD

**Issue by dmcminniwc** [ThrowTheSwitch/Unity#235]
Line 160:

`UnityPrintNumberUnsigned(  (_U_UINT)number  &  UnitySizeMask[((_U_UINT)style & (_U_UINT)0x0F) - 1]  );`

If you assume that someone could pass in a style not based on the definitions in unity_internals.h then `(style & 0x0F) - 1` could result in an index of 14 into `UnitySizeMask[]` which only has 7 elements (or 8 with 64 bit support).

**Comment by mvandervoord** [comment]
I suppose theoretically it could become 1 as well... though I don't see any of these things happening. Still, it should be simple enough to protect against. :)
