### ISSUE TITLE
Rename UNITY_SKIP_EXECUTION suggestions

### ISSUE THREAD

**Issue by jsalling** [ThrowTheSwitch/Unity#239]
This macro is internal to `unity.c`. Renaming it will not affect any interfaces.

When reading code this macro sounds confusing and its intent is unclear.
```C
void AssertFunction(params)
{
    int i, j;
    UNITY_SKIP_EXECUTION;
    …
```

I propose changing it to `RETURN_IF_FAIL_OR_IGNORE`.
Does this sound reasonable?

**Comment by mvandervoord** [comment]
Agreed. I like that much better!
