### ISSUE TITLE
malloc overrides and reserved identifiers

### ISSUE THREAD

**Issue by TheCount** [ThrowTheSwitch/Unity#24]
In the malloc overrides header unity_fixture_malloc_overrides.h, included by unity_fixture.h, the macro names malloc, calloc, realloc, and free are defined. This causes undefined behaviour _if_ &lt;stdlib.h&gt; is included prior to the definition, or included later with the definitions still present (C99 7.1.3p1 and p2, also ANSI C and C11 but I'll use C99 as a reference as it seems to be the most prevalent standard at this time).

Therefore, it should be documented that &lt;stdlib.h&gt; must not be included alongside unity_fixture.h.

On a more practical note, compiling unity_fixture.c with gcc 4.6.3 currently yields the warnings

<code>
unity_fixture.c: In function ‘unity_malloc’:
unity_fixture.c:185:5: warning: implicit declaration of function ‘malloc’ [-Wimplicit-function-declaration]
unity_fixture.c:185:21: warning: incompatible implicit declaration of built-in function ‘malloc’ [enabled by default]
unity_fixture.c: In function ‘release_memory’:
unity_fixture.c:208:5: warning: implicit declaration of function ‘free’ [-Wimplicit-function-declaration]
unity_fixture.c:208:5: warning: incompatible implicit declaration of built-in function ‘free’ [enabled by default]
</code>

on x86_64 glibc 2.15. While unity_fixture.c takes care not to include &lt;stdlib.h&gt; before malloc and free are undefined (calloc and realloc seem to have been forgotten), the header &lt;string.h&gt; includes &lt;stdlib.h&gt; somewhere down in its belly. I believe this is a bug in glibc as the inclusion of &lt;string.h&gt; has no business of declaring malloc and friends. Nevertheless, it may be generally difficult for unity users to avoid the inclusion of <stdlib.h> when using unity_fixture.h. Maybe forced malloc failures are better implemented at the dynamic linker level (cf. LD_PRELOAD).

**Comment by mvandervoord** [comment]
Resolved. Memory is now separate from fixtures.
