### ISSUE TITLE
unity_test_summary.py does not list ignored tests using TEST_IGNORE()

### ISSUE THREAD

**Issue by dmcminniwc** [ThrowTheSwitch/Unity#259]
I have written some tests with Unity and while experimenting with the reporting I found that the python version of the unity_test_summary script does not list ignored tests when the `TEST_IGNORE()` assertion is used. It does list them if you use `TEST_IGNORE_MESSAGE(message);`. The number of ignored messages is correctly counted in the summary in both cases. My output is this when TEST_IGNORE is used:

    --------------------------
    UNITY IGNORED TEST SUMMARY
    --------------------------
    --------------------------
    UNITY FAILED TEST SUMMARY
    --------------------------
    path\to\file.c:296:test_Description:FAIL: Expected 6 Was 1
    --------------------------
    OVERALL UNITY TEST SUMMARY
    --------------------------
    52 TOTAL TESTS 1 TOTAL FAILURES 1 IGNORED

while with TEST_IGNORE_MESSAGE("foo") it is:

    --------------------------
    UNITY IGNORED TEST SUMMARY
    --------------------------
    path\to\file.c:275:test_AnotherTest:IGNORE: foo
    --------------------------
    UNITY FAILED TEST SUMMARY
    --------------------------
    path\to\file.c:296:test_Description:FAIL: Expected 6 Was 1
    --------------------------
    OVERALL UNITY TEST SUMMARY
    --------------------------
    52 TOTAL TESTS 1 TOTAL FAILURES 1 IGNORED

I think the reason for that is without the message the result in the output looks like this:

    path\to\file.c:275:test_AnotherTest:IGNORE

And in unity_test_summary.py, lines 88-90 it splits the line by colon and checks for 5 parts. Since there are only 3 colons it results in only 4 parts. Instead of line 90 being `continue` it could fill in the missing fields from the split to be empty strings and let the subsequent checks reject lines that do not have the status strings. I think that's how the ruby version works. For example `parts.append("" * (5 - len(parts)));` would seem to generate the correct list but I can't get it to work in the script (not a Python programmer :).

The other alternative would be to change the reporting of PASS and IGNORE so that they always print the last colon, bringing the lines back up to 5 components. But that might break people's existing build systems depending on how they parse the output.

**Comment by mvandervoord** [comment]
Does 1782BAB fix your issue?

**Comment by dmcminniwc** [comment]
Yes it does.

**Comment by mvandervoord** [comment]
Awesome. I love it when something is simple. :)
