### ISSUE TITLE
Test runner generation does not take in account the mock file's prefix/suffix

### ISSUE THREAD

**Issue by Ninho67** [ThrowTheSwitch/Unity#263]
In generate_test_runner.rb, here is what I can read in find_mocks :

`mock_headers << include_path if (include_file =~ /^mock/i)`

So the script supposes that all mock headers start with lower case 'mock'. However, and given the fact that a yml file can be provided for generation, the script should check the cmock suffix/prefix option and use the appropriate value to detect mock_headers.

**Comment by mvandervoord** [comment]
It's flagged as case insensitive, so Mock, mock, mock_, MOCK_ or whatever will all work... but you're right that it should use the configured prefix.

**Comment by mvandervoord** [comment]
Fixed in commit 8a45ccf
