### ISSUE TITLE
No way to omit UNITY_OUTPUT_FLUSH

### ISSUE THREAD

**Issue by rikvdh** [ThrowTheSwitch/Unity#269]
Hi,

I'm not really able to omit the UNITY_OUTPUT_FLUSH, but I need to because my platform doesnt support it.

The only way to achieve this now is:

`-DUNITY_OUTPUT_FLUSH=// -DUNITY_OMIT_OUTPUT_FLUSH_HEADER_DECLARATION`

This seems not very intuitive and pretty.

Perhaps a option to omit the output flush at all is desirable.

Also the `#ifndef` here is unnecessary: https://github.com/ThrowTheSwitch/Unity/blob/master/src/unity_internals.h#L265
since it is always defined here:
https://github.com/ThrowTheSwitch/Unity/blob/master/src/unity_internals.h#L254-L257

Greetings,

Rik

**Comment by mvandervoord** [comment]
You could have just defined -DUNITY_OUTPUT_FLUSH and -DUNITY_OMIT_OUTPUT_FLUSH_HEADER_DECLARATION... but honestly that's really tedious. Instead I've switched back to the default being that there is no flush, but made a shortcut for the most common case, which is UNITY_USE_FLUSH_STDOUT.

See commit 8723d50
