### ISSUE TITLE
Unity Fixture non-verbose output

### ISSUE THREAD

**Issue by schulz-m** [ThrowTheSwitch/Unity#270]
I am fairly new to the Unity framework so I am just throwing it in as an issue - For the the `UnityFixture` extension - why is a `'.'` printed on these lines in `extras/fixture/src/unity_fixture.c` for the `UnityTestRunner`?

    if (!UnityFixture.Verbose)
        UNITY_OUTPUT_CHAR('.');
    else
    {
        UnityPrint(printableName);
    }

This is rather annoying, as the output will be flooded with dots when the tests are passing.

**Comment by Letme** [comment]
What else would you propose to be less annoying as a progress output?

**Comment by mvandervoord** [comment]
The fixture add-on is there for the purpose of acting like cppUTest. This behavior is there to emulate the way cppUTest outputs data during a test. We could add a silent mode for those who want to partially emulate fixtures but don't want the output? The default would have to remain as is, though.

**Comment by schulz-m** [comment]
Ok thanks for answering - for me the only purpose was ease of use, I wasn't aware of the cppUTest. Well we would need something like a "silent mode" for our application, seems a bit like an overkill to me though xD
