### ISSUE TITLE
Convert documentation to a structured text format instead of binary

### ISSUE THREAD

**Issue by wolf99** [ThrowTheSwitch/Unity#273]
Comment https://github.com/ThrowTheSwitch/Unity/issues/194#issuecomment-287890661 mentions the possibility of converting documentation to some structured text format instead of the current binary format (PDF).

I would be willing to put in leg work on this but wanted to discuss the most suitable format as I am mainly only experienced with markdown of those mentioned in the linked issue (markdown, restructured text, aciidoc, etc). I currently don't see any benefit to one of those over the others but I may well be wrong!

One consideration may be the ease with which PDF's could subsequently be programmatically generated from the resulting documents, if such a thing was required (but the merits of such a requirement could also be discussed).

**Comment by wolf99** [comment]
Another consideration might be if some of the documentation might be able to be automatically from code comments (i.e. the work to then be done her would be to break down the current documentation fitting this, into code comments).

**Comment by mvandervoord** [comment]
Do you know of any projects that have done this well? I have been disappointed by most of the automatically generated docs for the projects I've seen.

**Comment by bjones1** [comment]
To advertise my own (free - GPL) tools a bit, [CodeChat](http://pythonhosted.org/CodeChat/) transforms reStructuredText comment in source code to web pages using Sphinx, which produces beautiful documentation directly from the source code -- [here's](http://pythonhosted.org/CodeChat/CodeChat/CodeToRest.py.html) an example. It supports C/C++, Ruby, and many more languages.

**Comment by wolf99** [comment]
After a quick whiz around Google, on the point of generation from inline documentation in source code I can see two other options that jump out:

- Sphinx, uses restructured text, documents C and Ruby via 'Domains'  (I have zero experience with Sphinx or rst)
- Doxygen, uses markdown, doesn't document Ruby (But I have some little experience with this)

It is true however (at least in my experience of Doxygen and my quick perusal of doc gen websites this morning), that generating beautiful PDFs from takes, at the very least, considerable configuration twiddling. HTML and textual output is quite a bit easier though.

**Comment by Letme** [comment]
I can add to this discussion. I have been using sphinx for quite some time now to convert reStructuredText to html document, but it also supports .pdf. What is amazing about Sphinx is the amount of plugins -> from plantuml to various plugins for whatever you might imagine. Source is similar to markdown and nice to diff in merge/pull requests. There are also some tools to convert doc to rst which work fine without any pictures or graphs (which I doubt I seen in current docs).

If you do not use anything special (just text and headings), then simple Markdown (GFM) documentation with links will render fine on GitHub.

**Comment by wolf99** [comment]
I forked and replaced the PDFs's to give an idea of markdown versions would be like. Cheat sheet would still remain as markdown does not do layout. [https://github.com/wolf99/Unity/tree/pdf-to-markdown/docs](https://github.com/wolf99/Unity/tree/pdf-to-markdown/docs). Could make a PR of the branch if suitable?

**Comment by wolf99** [comment]
Now also with a reStructuredText branch. We can haz all the options! [https://github.com/wolf99/Unity/tree/md-to-rst/docs](https://github.com/wolf99/Unity/tree/md-to-rst/docs). Take your pick.

My 2c: having now some small bit more experience with rst, I prefer writing in md as it's a lot easier to get something done quickly without interrupting ongoing work too much. Rst just seems more... fiddly.

**Comment by mvandervoord** [comment]
@wolf99, I'm really liking the markdown docs. I'd like to make those the official versions. Two questions:

(1) Did you automate the conversion or did you do that manually?
(2) Can you put together a pull request of your markdown files?  :)

**Comment by wolf99** [comment]
@mvandervoord  I did the md manually because I'm kinda used to using markdown. Converting from the md to rst I just used Pandoc. Think I added the Pandoc command I used to that commit message. Hold on a sec.... yep: 

```sh
> pandoc --from markdown --to rst --columns 80 --output <file-name>.rst <file-name>.md
```
