### ISSUE TITLE
Only the first test runs from the command prompt

### ISSUE THREAD

**Issue by Darren996** [ThrowTheSwitch/Unity#279]
From a prompt I can run this:
xterm -T ./SomeProgram -e /usr/bin/cb_console_runner LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. /home/pi/Documents/Codeblocks_Projects/SomeProgram_WithUnitTests/bin/UnitTest/SomeProgram

...and it works just fine.  From a terminal window if I run ./SomeProgram it stops after the first test.  I did try to take away the xterm -T from the above but it does the same thing.  What am I doing wrong?

**Comment by mvandervoord** [comment]
I'm assuming you're talking about a terminal window from within Codeblocks?

In either case, it seems like your test is aborting for some reason. This is the same file (without rebuilding it?). 

I'm not really a Codeblocks person, but I will do my best to help you debug this.

**Comment by Darren996** [comment]
Thank you so much!  

Just a regular prompt.  Codeblocks is irrelevant really.  It works fine and the unit test run fine there.  When I run it from a regular terminal window in raspbian the first test passes and then it stops.  The next test doesn't appear to run at all.  I put a printf in there and it doesn't hit it.  The reason I am inquiring about this is because I'm trying to run the test from a terminal window on an embedded device.  How can I find out what is causing the test to abort?

**Comment by mvandervoord** [comment]
Debugging a test is (unfortunately) not a simple task, particularly when done remotely. 

Can you post the contents of your test file? If not, can you reproduce it with a smaller test file?  I'd just like to verify everything is built the way I would expect it. I can't think of a particular thing that would cause this issue, but I'm hoping something jumps out at me when I see it. ;)

**Comment by Darren996** [comment]
Me too! 

`int test_tag_functions_main()
{
    UnityBegin("test/test_tag_functions.c");
    //need to write tests for if search goes out of bounds
    RUN_TEST(test_compareTwoTagsSimilar_true);
    RUN_TEST(test_compareTwoTagsSimilar_SingleTagNull);
    RUN_TEST(test_compareTwoTagsSimilar_BothTagsNull);
    RUN_TEST(test_compareTwoTagsSimilar_TagsDifferentLength);
    RUN_TEST(test_compareTwoTagsSimilar_TagsSameLengthButDifferent);
    RUN_TEST(test_compareTwoTagsSimilar_OutOfBounds);

    return UnityEnd();
}
`

Then the test themselves are just like so:
`void test_compareTwoTagsSimilar_true()
{
    char tag1[12] = "123456789012";
    char tag2[12] = "123456789012";
    TEST_ASSERT_TRUE(compareTwoTagsSimilar(&tag1, &tag2, 12, 12));
}`

**Comment by Darren996** [comment]
Okay.  Apparently this is the command to run from a terminal window?

`/usr/bin/cb_console_runner LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. /home/pi/Documents/Codeblocks_Projects/SomeProgram_WithUnitTests/bin/UnitTest/SomeProgram`  That works!

**Comment by mvandervoord** [comment]
Wow. Interesting. Maybe someone will stumble on this and explain to both of us why that makes a difference!  ;)

**Comment by Darren996** [comment]
Oh!  LOL that is a CodeBlocks program.  The only weird thing I am doing is
starting and stopping mockserver on another thread.

**Comment by mvandervoord** [comment]
Cool. Well, I am glad you got it sorted out.

**Comment by Darren996** [comment]
Well it runs on the SBC that has CodeBlocks but the other SBC I can't install it.

**Comment by mvandervoord** [comment]
I was originally wondering if it's some undefined behavior in test_compareTwoTagsSimilar_SingleTagNull itself. If you were to comment out the contents of that test, does it then get run?

**Comment by Darren996** [comment]
Oh gosh it was totally my fault.  Thanks for helping me.   Unity is awesome!

**Comment by mvandervoord** [comment]
Ha!  No problem. The downside of a test framework that is in an unsafe language is that if the testing code crashes, so does the test. ;) It gets us all! Best of luck!
