### ISSUE TITLE
unity_fixture tests don't build

### ISSUE THREAD

**Issue by malsyned** [ThrowTheSwitch/Unity#3]
When I run 'rake' in extras/fixture, I get the following error:

rake aborted!
No such file or directory - /home/malsyned/projects/tdd-embedded/Unity.playground/extras/fixture/../../targets/gcc.yml

If I fix this error by changing DEFAULT_CONFIG_FILE in rakefile.rb from gcc.yml to gcc_32.yml, I move past that point but get a different failure:

gcc: ../../src/Unity.c: No such file or directory
gcc: no input files
rake aborted!

This turns out to be a capitalization issue - unity.c is all lower-case but the rakefile refers to capital 'U' Unity.c I fixed this by editing rakefile_helper.rb and modifying line 151 to read
    src_files << '../../src/Unity.c'

But it still doesn't build!

/usr/lib/gcc/i486-linux-gnu/4.4.3/../../../../lib/crt1.o: In function `_start':
(.text+0x18): undefined reference to `main'
collect2: ld returned 1 exit status
rake aborted!

This final failure, I fixed by adding the following after line 150:
    src_files += Dir[HERE+'test/main/*.c']

This is with Unity b7d9d00

**Comment by aburks** [comment]
This still exists in latest master (e40530d59f1a0bcf08639c2220d8ad0bacec5026).
