### ISSUE TITLE
Seg fault doesn't throw in unity?

### ISSUE THREAD

**Issue by terencechow** [ThrowTheSwitch/Unity#305]
I'm new to C and i'm trying to get my test to display as failing with unity. Instead unity appears to be not displaying anything when it fails on a seg fault.

For example my test has this erroneous code:
```
char buff[5]; <-- purposely set array to 5
sprintf(buf, "Empty stack should return %d.", STACK_EMPTY); <-- has more than 5 chars
```

and I get this error messagae when the test runs: 
```
./build/test_stack.out > build/results/test_stack.txt 2>&1
/bin/sh: line 1: 32584 Abort trap: 6           ./build/test_stack.out > build/results/test_stack.txt 2>&1
make: [build/results/test_stack.txt] Error 134 (ignored)
-----------------------
IGNORES:
-----------------------

-----------------------
FAILURES:
-----------------------
// NOTE: NOTHING HERE
```

Under Failures my test that caused a segfault doesn't display. It's completely skipped that test in the results. 

Is there a way to show this test as failing?

**Comment by mvandervoord** [comment]
Unity is only a C library. As such, once it seg-faults, it's no longer in control of anything, and can't report anything... hence that test never gets logged.

I'm not sure how you are coordinating the tests. Are you running them from a makefile? Using a rakefile? If you're using something fairly powerful (like rake), it is definitely possible to capture the crashed file and report that it failed after a particular test (if you make the script parse out the test names, it could even do a good job guessing that the next test is the one that crashed. This is functionality we're baking into Ceedling, actually.

**Comment by herrmanthegerman** [comment]
Hi, 
I'd also like to see unity/ceedling to handle segfaulted code-under-test.

For example, if I add the following code to the tests:

```C
void test_parseCommandLine_null(void) {
	char *line = 0;
	ret = parseCommandLine(line, &cmd);

	TEST_ASSERT_NOT_EQUAL (0, ret);
}
```
and run `ceedling`, I get the following overall test result:

> --------------------
> OVERALL TEST SUMMARY
> --------------------
> TESTED:  16
> PASSED:  16
> FAILED:   0
> IGNORED:  0



I have two concerns with this result:
a)  there are no failed tests. Obviously, unity/ceedling do not regard the segfault that occurs.
b) the test run is incomplete. Without the `test_parseCommandLine_null` test, there are 22 tests.

I believe that null-pointer issues are common in C programms and therefore theses should be covered by testscases, too, without interfering with the test framework. In other words, I'd like to see unity/ceedling to handle segfault more gracefully.

**Comment by mvandervoord** [comment]
This issue is to be handled in Ceedling.
