### ISSUE TITLE
Warnings when -Wfloat-equal is used with gcc 7

### ISSUE THREAD

**Issue by selsky** [ThrowTheSwitch/Unity#314]
I'm building Unity 2.4.3 with gcc 7.2.0 and I have `-Wfloat-equal` enabled:
```
unity.c: In function 'UnityPrintFloat':
unity.c:271:34: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
     if (number < 0.0f || (number == 0.0f && 1.0f / number < 0.0f))
                                  ^~
unity.c:278:16: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
     if (number == 0.0f) UnityPrint("0");
                ^~
```
Also, in the first case, if number is zero, then 1/0 is undefined/infinite.

**Comment by jlindgren90** [comment]
Hi, I wrote this part of the code.  The intent is to print +0 and -0 differently from all other floating-point values.  That's the point of the comparison with zero, which is well-defined as far as I know.  Zeroes are a special case in all floating-point representations that I know of.

> Also, in the first case, if number is zero, then 1/0 is undefined/infinite.
It's +INF (1/+0) or -INF (1/-0), which are also special case values.  The point here is to be able to distinguish between +0 and -0.

Do you have a suggestion for a way to get rid of the warning?

**Comment by mvandervoord** [comment]
I've undone support for -0, both because it relied on undefined behavior, and because it's not even something that exists for some targets (C says it *may* exist, depending on the floating point system used). Instead, we're printing all of them as 0.
