### ISSUE TITLE
Outdated config options (e.g. UNITY_SUPPORT_WEAK) in "example/unity_config.h"

### ISSUE THREAD

**Issue by rstahn** [ThrowTheSwitch/Unity#315]
The example configuration file "example/unity_config.h" contains the option UNITY_SUPPORT_WEAK for configuration of "weak" support, but Unity is actually using the define UNITY_WEAK_ATTRIBUTE. I cannot tell, which name is actually the "better" one, but either the example config file or the code needs to be updated to be consistent.

**Comment by mvandervoord** [comment]
I believe you are misunderstanding it. UNITY_SUPPORT_WEAK is the public interface for enabling weak support. It is the opposite of UNITY_NO_WEAK.

UNITY_WEAK_ATTRIBUTE is defined based on those features as well as what it could surmise based on your compiler. It's used internally and is not meant to be externally defined.

**Comment by rstahn** [comment]
Well, i tried to use UNITY_SUPPORT_WEAK instead of UNITY_WEAK_ATTRIBUTE but to no success. If I search the unity package (Release v2.4.3) i find no references to UNITY_SUPPORT_WEAK outside "unity_config.h". Where is UNITY_SUPPORT_WEAK translated into UNITY_WEAK_ATTRIBUTE?

**Comment by mvandervoord** [comment]
Hm. I must apologize. It appears we went half-way through a change and didn't finish it or something. You are absolutely correct. It's a weird hybrid of having to define both for some things right now. I'll reopen this and try to clean this up soon.

Thanks for bringing this up, and for being persistent when I was feeding you (unintentional) lies. :)

**Comment by rstahn** [comment]
No problem. We really enjoy using Unity - so this just my little contribution to the project. :-)

**Comment by rstahn** [comment]
Looking at the blame history of `unity_config.h` and `unity_internals.h` I am now pretty sure, that `UNITY_SUPPORT_WEAK` has been replaced by `UNITY_WEAK_ATTRIBUTE` and `UNITY_WEAK_PRAGMA` with commit cadee02e792bbb50b63c1fe881664e175a61d901 about 4 years ago. 
Looks to me like only the example `unity_config.h` needs to be updated.

**Comment by rstahn** [comment]
If I'm not mistaken, the description in `unity_config.h` is actually originating from an older version of `UnityConfigurationGuide.md`. Is there any tool to convert from Markdown to C-style comments which I am not aware of?

**Comment by rstahn** [comment]
According to the discussion in #438 the whole support for `weak` has been dropped with #453 / #454. That's fine with me, but it looks like `examples/unity_config.h` still contains references to the outdated `UNITY_SUPPORT_WEAK`. Any reason why this issue has been closed without updating `examples/unity_config.h`?

**Comment by mvandervoord** [comment]
Thanks! I've fixed it now. :)

We didn't have a test which would notice things in comments, unfortunately... so this was just an oversite. :)
