### ISSUE TITLE
unity_to_junit.py  documentation or example?

### ISSUE THREAD

**Issue by ssj71** [ThrowTheSwitch/Unity#316]
I've been using Unity with the unity_fixture framework added for unit testing my embedded code. So far its been great, but our testing department wants the output in junit format to upload to testrail. I don't know tons about it this stuff, only that testing requested it. I've seen reference to the script auto/unity_to_juint.py in [this SE thread](https://stackoverflow.com/questions/43583966/unity-test-on-embedded-systems-to-web-output)  but haven't a clue what to do with it. Is there an example or a document somewhere that can help me figure it out?

I understand its probably easier with ceedling but we've already got our build system set up and would rather not have to redo everything.

Please be patient with my newbishness. :) Thanks!

**Comment by ssj71** [comment]
After some hunting, I think the problem is I'm not sure how to configure unity's output to make me a *.testpass or *.testfail file. I see in https://github.com/ThrowTheSwitch/Unity/blob/master/src/unity.h#L80 some options for output config, but not much. It mentions the default output goes to stdout, but no mention of how to do anything else.

**Comment by ssj71** [comment]
Ok, I dug some more and realized I first needed to pass the -v option to the test binaries. This then generates the "TEST(...) PASS" strings that the scripts look for. I found that my tests were printing to stdout which messed up the parsers, but redirecting those messages to stderr made a nice clean output on stdout. Injecting that to a log I was able to run the ruby script auto/parse_output.rb with the -xml option and it made a beautiful report.xml that I can upload as required.

Sorry for the noise, but thanks for the solutions (I just had to find them). A suggestion though is a little documentation outside of the source on the CLI options of the UnityMain function would be helpful.

**Comment by dankegel** [comment]
I didn't have to pass -v to the binaries; I just had to pass -v to 'meson test'.  The binaries are already verbose.

**Comment by mr-potato-head** [comment]
> Ok, I dug some more and realized I first needed to pass the -v option to the test binaries. This then generates the "TEST(...) PASS" strings that the scripts look for. I found that my tests were printing to stdout which messed up the parsers, but redirecting those messages to stderr made a nice clean output on stdout. Injecting that to a log I was able to run the ruby script auto/parse_output.rb with the -xml option and it made a beautiful report.xml that I can upload as required.
> 
> Sorry for the noise, but thanks for the solutions (I just had to find them). A suggestion though is a little documentation outside of the source on the CLI options of the UnityMain function would be helpful.

Hi @ssj71, I'm starting to work with Unity for a RISC-V embedded project. I can compile and run my test binary with CMake.
Here, is my output:
```
/home/test/Repos/unity_cmake/unity_tests.c:8:test_sum_should_sum:FAIL: Expected 40 Was 30

-----------------------
1 Tests 1 Failures 0 Ignored 
FAIL
```

I have exactly the same output with or without the 'v' argument.
Can you explain me how you generate the .testpass/.testfail files please ?
 Thanks in advance
