### ISSUE TITLE
Runner generator doesn't allow string literals

### ISSUE THREAD

**Issue by austinglaser** [ThrowTheSwitch/Unity#328]
A parametrized test of the format

```C
TEST_CASE("hi")
void test_something(char const * str)
{
    TEST_ASSERT_EQUAL_STRING("hi", str);
}
```

does not compile.

The culprit appears to be [this line](https://github.com/ThrowTheSwitch/Unity/blob/master/auto/generate_test_runner.rb#L95) of `find_tests()` in `generate_test_runner.rb`, where literal strings are scrubbed out of the source.

I understand (I think) the point of removing string literals, since they have the potential to contain characters that will confuse later regex parsers.  However, there's got to be a better way to go about this. At a minimum, the current scrubbing regex doesn't handle strings containing quotes -- for instance:

```C
TEST_CASE("{\"field\": 1234}")
void test_handles_json(char const * json)
{
    /* ... */
}
```

will thoroughly break the parser.

**Comment by art-of-dom** [comment]
This should be closed as #380 fixed this
