### ISSUE TITLE
suiteSetUp() and suiteTearDown() callbacks never invoked

### ISSUE THREAD

**Issue by manuargue** [ThrowTheSwitch/Unity#336]
The callback functions `suiteSetUp` and `suiteTearDown` declared at `unity.h` are never invoked. This can be checked with a simple search on the `src` folder: `suiteSetUp()`.

According to the comments in the source code:
```
/* These functions are intended to be called at the beginning and end of an
 * entire test suite.  suiteTearDown() is passed the number of tests that
 * failed, and its return value becomes the exit code of main(). */
```
If these two functions must be invoked manually after `UNITY_BEGIN()` and before `UNITY_END()` respectively, it should be noted on the comments.

For `setUp` and `tearDown` callbacks, the comments are similar but those are invoked automatically:
`/* These functions are intended to be called before and after each test. */`

**Comment by mvandervoord** [comment]
suiteSetup and suiteTeardown are called by the runner which is generated by the automatic test runner generator script, if that is being used.

You're correct that this should be better described in the documentation. I'm leaving this issue open until the docs are improved.

Thanks for the help!

**Comment by manuargue** [comment]
Thanks for clarifying :+1: 

Is there any reason why you decided not to invoke the test suite callbacks automatically?

**Comment by mvandervoord** [comment]
:) That is correct.
