### ISSUE TITLE
Add unit tests for LESS_OR_EQUAL and GREATER_OR_EQUAL asserts

### ISSUE THREAD

**Issue by rstahn** [ThrowTheSwitch/Unity#339]
While investigating on #337 i noticed, that there are currently no unit tests for the following asserts:
- `TEST_ASSERT_LESS_OR_EQUAL_*`
- `TEST_ASSERT_GREATER_OR_EQUAL_*`

Furthermore, there are currently only single tests for checking the "failing condition" of the following asserts:
- `TEST_ASSERT_LESS_THAN_*`: only `testNotLessThan()` covered
- `TEST_ASSERT_GREATER_THAN_*`: only `testNotGreaterThan()` covered

**Comment by mvandervoord** [comment]
Thanks @art-of-dom for resolving this issue!
