### ISSUE TITLE
Feature proposal: optional user-defined formatting of filename and line in Unity output

### ISSUE THREAD

**Issue by rstahn** [ThrowTheSwitch/Unity#342]
Unity output contains references to source code filenames and line numbers for each successful test case or failed assert. If run from within an IDE it is desirable to have the IDE create a link to the referenced file and line within the output window. This usually requires some special formatting - depending on the IDE.

#### Examples:
- Eclipse automatically converts the output `(<file>:<line>)` to a link
- IAR Embedded Workbench shows `<SRCREF line=<line> file="<file>">some text</SRCREF>` as link

I was thinking about extracting the printing of filename and line out of `UnityTestResultsBegin()` into a separate function `UnityPrintFileAndLine()` defined as weak symbol (if available) which can be overridden by the user. The default implementation should of course keep the current output to avoid breaking all those result converter scripts that are parsing the output.

What do you think? Is there any reason not to do it?

**Comment by andre-hartmann** [comment]
* Qt Creator likes the format `file://<file>:<line>`

If weak symbols don't work (everywhere), we could register a callback function, too.

**Comment by mvandervoord** [comment]
Done. I added all three listed above
