### ISSUE TITLE
test in C++ (proposal patch)

### ISSUE THREAD

**Issue by alef75** [ThrowTheSwitch/Unity#344]
I'm working on a embedded Arm platform in which we use mixed C and C++ code, so we need to make unitest on both.
I'm successful build the C++ test code, but I've to add in the testrunner each time it is generated the following statement: 
#ifdef __cplusplus 
extern "C"{
#endif""
....
#ifdef __cplusplus
}
#endif"

in attach the patch to apply to add it to the testrunner.rb

[cgc_generate_test_runner.rb.patch.txt](https://github.com/ThrowTheSwitch/Unity/files/2273113/cgc_generate_test_runner.rb.patch.txt)

**Comment by mvandervoord** [comment]
I love it! Thanks!

**Comment by alef75** [comment]
I'm glad it could be useful

**Comment by mvandervoord** [comment]
Completed in 9987824da794ce53ff77137f237dcebec91f3dd6
