### ISSUE TITLE
How to generate test runners for grouped tests?

### ISSUE THREAD

**Issue by cy18** [ThrowTheSwitch/Unity#358]
Hi, I used macros provided in unity_fixture.h to define tests by group, and tried to generate test runner by generate_test_runner.rb. It seems it's not supported. Is it possible to generate test runner for grouped tests? Did I missed anything?

Thank you.

**Comment by mvandervoord** [comment]
No, it's not. The unity_fixture file is an addon to make Unity act like cppUTest for those who like that behavior. As such, it doesn't do any of the more advanced things that Unity does naturally (like autogenerate test runners).
