### ISSUE TITLE
Unity main example has unintended array overrun

### ISSUE THREAD

**Issue by quantum-leaps** [ThrowTheSwitch/Unity#360]
The main examples shipping with Unity (examples/example_1/src/ProductionCode.c and examples/example_2/src/ProductionCode.c) seem to have an unintended array overflow error. This error might cause the first example test "FindFunction_WhichIsBroken_ShouldReturnZeroIfItemIsNotInList_WhichWorksEvenInOurBrokenCode" to fail, whereas it is clearly intended to work (pass). For example, the test fails when the memory is pre-filled with 0xFF.

The code accesses the array element `NumbersToFind[9]`, which is one *past the end* of the array (the array is defined as `int NumbersToFind[9] = …`, which means that the legal indexes are 0..8).

The proposed "fix" in the "ProductionCode.c" is to change the while() loop from `while (i <= 8) i++;` to `while (i < 8) i++;` After this change, the tests will behave consistently on any machine. The `FindFunction_WhichIsBroken()` function remains still obviously broken, but in the "intended" way.

**Comment by mvandervoord** [comment]
Thanks!
