### ISSUE TITLE
Use macros in test runner generator

### ISSUE THREAD

**Issue by kl-cruz** [ThrowTheSwitch/Unity#367]
Hi,
My idea is to change functions in generate_test_runner.rb to macros to give possibilities of (for example) providing output data in another format.
There are two important functions in unity framework: UnityBegin and UnityEnd. They can be redefined using:
https://github.com/ThrowTheSwitch/Unity/blob/master/src/unity_internals.h#L685
and for UnityEnd:
https://github.com/ThrowTheSwitch/Unity/blob/master/src/unity_internals.h#L689

There are functions used in test runner generator:
https://github.com/ThrowTheSwitch/Unity/blob/master/auto/generate_test_runner.rb#L368
https://github.com/ThrowTheSwitch/Unity/blob/master/auto/generate_test_runner.rb#L382

I think it is change easy-to-do. What do you think about it? Is it affecting other parts of the Unity code?
Thanks!

**Comment by mvandervoord** [comment]
I 100% agree. I don't know how I've missed this in the past. Thanks for the thought!

Are you in a position to put together a PR for that change? Switching the generator to use the macros instead of the direct function calls should be fairly straightforward, I believe?
