### ISSUE TITLE
Move License to Project Root

### ISSUE THREAD

**Issue by danyeaw** [ThrowTheSwitch/Unity#369]
GitHub can automatically show which license your project is on the main page if you put your license in the root of the project:
https://help.github.com/articles/licensing-a-repository/

I had to go dig around to find it in the docs, and then compare it with the MIT license. This would make it much more clear to everyone visiting your project what license it is.

I can submit a PR if there is agreement to move it. 👍

**Comment by mvandervoord** [comment]
sounds good to me.
