### ISSUE TITLE
Improvments: Define Macro for UnityPrint

### ISSUE THREAD

**Issue by slumdroid** [ThrowTheSwitch/Unity#372]
To write an output I used this:
UnityPrint(Unity.CurrentTestName);

for UnityPrint("/n") there is UNITY_PRINT_EOL();
Can you expose a new macro for UnityPrint, please?

Thanks

**Comment by mvandervoord** [comment]
Completed. There is now a TEST_MESSAGE("hello") macro for writing to unity's output stream. It will also record the file and line as part of the message.
