### ISSUE TITLE
Having bug while getting up and running

### ISSUE THREAD

**Issue by mahmad123** [ThrowTheSwitch/Unity#373]
### Description
I am currently configuring my system to use Unity to run unit testing on my project files, and i am using rake to run the builds.  I have got my setup building, but i get the following error when i build test executables.  
```dos
c:/myprograms/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../libmingw32.a(main.o):(.text.startup+0xa0): undefined reference to `WinMain@16'
collect2.exe: error: ld returned 1 exit status
rake aborted!
```  
i can provide more details on my setup, or source files, but I am not even sure what error this even is.  Could someone help explain this?

**Comment by farrrb** [comment]
I know this sounds like a really dumb question, but do you have a **main** function present? I get the same error on my windows machine every time I forget to link without a main function present:

e.g.:
```
[2/2] Linking C executable my_tests\my_test.exe
FAILED: my_tests/my_test.exe
cmd.exe /C "cd . && C:\Qt\Qt5.8.0\Tools\mingw530_32\bin\gcc.exe    my_tests/CMakeFiles/my_test.dir/test.c.obj  -o my_tests\my_test.exe -Wl,--out-implib,my_tests\libmy_test.dll.a -Wl,--major-image-version,0,--minor-image-version,0  src/libunity.a -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
C:/Qt/Qt5.8.0/Tools/mingw530_32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../i686-w64-mingw32/lib/../lib/libmingw32.a(lib32_libmingw32_a-crt0_c.o):crt0_c.c:(.text.startup+0x39): undefined reference to `WinMain@16'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Comment by mahmad123** [comment]
I did resolve this by including my own main() function.

**Comment by Tosh-Jaiswal** [comment]
I was also facing the same problem but after restarting pc it was solved.

**Comment by Iamjanardan** [comment]
The main issue is that "YOU DIDN'T save YOUR FILE", first save your cpp file then enter the command (g++ file.cpp) or run it.
Usually, this error occurs when file was not saved.

**Comment by vulpinefoxxo** [comment]
> 
> 
> The main issue is that "YOU DIDN'T save YOUR FILE", first save your cpp file then enter the command (g++ file.cpp) or run it.
> Usually, this error occurs when file was not saved.

this was it thanks

**Comment by GRim7262** [comment]
> The main issue is that "YOU DIDN'T save YOUR FILE", first save your cpp file then enter the command (g++ file.cpp) or run it.
> Usually, this error occurs when file was not saved.

Thanks a lot.
