### ISSUE TITLE
How about a release?

### ISSUE THREAD

**Issue by kykrueger** [ThrowTheSwitch/Unity#384]
It has been quite some time since there has been a release. How about rolling one out?

**Comment by mvandervoord** [comment]
:) indeed!

**Comment by jethrodaniel** [comment]
Additionally, It'd be nice if the [LICENSE](https://github.com/ThrowTheSwitch/Unity/blob/master/LICENSE.txt) was updated to 2019.

**Comment by kykrueger** [comment]
Anything I can do to help? I'm also looking for more documentation about writing plugins. I'm hoping to write one for [fbinfer](https://github.com/facebook/infer/issues/1054).

**Comment by dpostorivo** [comment]
Is there anything blocking this that people can help with? I'd like to utilize some of the newer fixes soon.

**Comment by mvandervoord** [comment]
My apologies. There are a couple minor features and tweaks I want to make and then I plan to push a release. I believe I can get on this next week. Fingers crossed!

**Comment by dpostorivo** [comment]
Sorry to keep pining this, but any updates or blockers that the community can help with? I'd love to help unblock a Unity, Ceedling, and Cmock release and I'm sure others would too.

**Comment by mvandervoord** [comment]
Are any of you in a position to grab the latest versions of everything from the repos and verify they still work on your local projects? I'd love to have a little bit of validation that it's not breaking anyone's current setup.

**Comment by dpostorivo** [comment]
I can start it tonight should have some feedback by tomorrow. Long term we may want to set up repo that links to open source examples and can be used to gauge if the latest Ceedling/Cmock/Unity breaks anything .

It's a long term path, but hopefully it will make testing releases like this easier.

**Comment by dpostorivo** [comment]
Running it on projects local works really well out of the box with tests designed for the previous version. I've also confirmed the Test Parameter strings work and the junit report which generated them was also valid. I've also tested some of the new gcov options.

**Comment by mvandervoord** [comment]
Thanks so much! I appreciate that, @dpostorivo !
