### ISSUE TITLE
Unity and Static Analysis

### ISSUE THREAD

**Issue by shreyasbharath** [ThrowTheSwitch/Unity#39]
A major issue we have with tests written with Unity, is that it throws a lot of compiler warnings on GCC and also with static analysis tools such as PC-Lint.

Here's an example error thrown by PC-Lint -

    call to function 'TEST_Init_GROUP_RUNNER_runAll()' not made in the presence of a prototype

    'TEST_TestGroup_ExampleTestCase_run()' not made in the presence of a prototype

Another issue found by PC-Lint is with the below function in unity_internals.h/.c. It complains of 'Suspicious pointer-to-pointer conversion (area too small)' when a UINT8, UINT16 or INT8, INT16 arrays are passed to this function using 'UNITY_TEST_ASSERT_EQUAL_INT8_ARRAY' and friends.

void UnityAssertEqualIntArray(const _U_SINT* expected,
                              const _U_SINT* actual,
                              const _UU32 num_elements,
                              const char* msg,
                              const UNITY_LINE_TYPE lineNumber,
                              const UNITY_DISPLAY_STYLE_T style);

This can be fixed by casting it to a void * pointer instead of a U_SINT* pointer.

Can we do something about these errors and make Unity static analysis (and maximum compiler warning) friendly?

**Comment by jsalling** [comment]
This is an older issue, but after looking at all the lint errors above, I think these have all been fixed.
Most are addressed in 3399bba2.
@mvandervoord Will you close?
