### ISSUE TITLE
Implicit declaration of function ‘UNIT_BEGIN’

### ISSUE THREAD

**Issue by Mulan-94** [ThrowTheSwitch/Unity#395]
Hi,
I get 
`warning: implicit declaration of function ‘UNIT_BEGIN’ [-Wimplicit-function-declaration]
     UNIT_BEGIN()`
and
``undefined reference to `UNIT_BEGIN'``
Even after including `unity.h` when running a simple test.
I am running gcc on a linux machine.
Any assistance please? 
Thanks.

**Comment by mvandervoord** [comment]
I'm guessing you hand-built the test runner for this? The name of the function is UNITY_BEGIN, not UNIT_BEGIN (note the Y)

**Comment by Mulan-94** [comment]
Ooh, my bad, thank you! :100:

**Comment by mvandervoord** [comment]
:) no problem.
