### ISSUE TITLE
Include Code Coverage Infrastructure

### ISSUE THREAD

**Issue by alejmrm** [ThrowTheSwitch/Unity#40]
After working with unity for a while I am seeing that some of my test are not covering all the cases that I should. So this request is to include some sort of code coverage infrastructure in Untiy.

I don't have any specifics about how to implement this feature, but what I have seem in the web --wikipedia mainly, by searching for code coverage-- is some sort of file transformation on the fly to get an instrumented version of the file that you want to analyze, then run through your unit test harness, or some sort of this variation.

**Comment by hemaggopal** [comment]
Existing code invokes cov01 commands through ant. Now I have to exclude few files. covselect is throwing  the following error. Could someone provide pointers on this?
error: unknown option "--add \!**/filename.extn1.*/" 

_//Trying to exclude files with name "filename.extn1.*" in any folder_
<exec failonerror="false" failifexecutionfails="false" executable="covselect">
    <arg value="--add  \!**/filename.extn1.*/"/>
</exec>
_//Enabling the coverage_
<exec failonerror="false" failifexecutionfails="false" executable="cov01">
    <arg value="-1" />
</exec>
_//Build the files_
....
_//Disabling the coverage_
<exec failonerror="false" failifexecutionfails="false" executable="cov01">
    <arg value="-0" />
</exec>

**Comment by cvoltz** [comment]
Since the original issue was closed 3 years ago, it would probably be best if your new request was created as a new issue.
