### ISSUE TITLE
What about a coding style / code formatter for this project?

### ISSUE THREAD

**Issue by farrrb** [ThrowTheSwitch/Unity#405]
Everytime I do a change for this project I try to be a good boy-scout and leave the place a little cleaner. 😄 But I recently noticed that the indentation of the preprocessor macros for example is totally off. 
So here's my proposal: how about adding a code formatter configuration file (e.g. for clang format) in order to make sure the code is according to style before we do commits?

**Comment by mvandervoord** [comment]
:) Using Rubocop to check style of both ruby and C.

**Comment by austinbes** [comment]
Out of curiosity, what configuration do you use for Rubocop and C?

**Comment by mvandervoord** [comment]
I apologize. I've misspoken. 

The Ruby code is style-checked by Rubocop (you can find the style configuration in `test/.rubocop.yml`)

The C code is style-checked by AStyle. It's settings are in the `test/rakefile_helper.rb` (and currently are as follows):

- allman
- indent=spaces=4
- indent-switches
- indent-preproc-define
- indent-preproc-block
- pad-oper 
- pad-comma
- unpad-paren
- pad-header
- align-pointer=type
- align-reference=name
- add-brackets
- mode-c
- suffix=none

**Comment by austinbes** [comment]
Awesome, thanks!
