### ISSUE TITLE
TEST_ASSERT_EQUAL_STRING / UnityAssertEqualString stops checking on first \0 for any string

### ISSUE THREAD

**Issue by dueringa** [ThrowTheSwitch/Unity#407]
According to docs/UnityAssertionsReference.md, TEST_ASSERT_EQUAL_STRING 

> Asserts that the null terminated ('\0')strings are identical. *If strings are of different lengths* or any portion of the strings before their terminators differ, the assertion fails. Two NULL strings (i.e. zero length) are considered equivalent.

However, the "different length" part is not true currently, since the check goes (unity.c#L1263):

        for (i = 0; expected[i] || actual[i]; i++)

so if I compare `foo` with `foo2`, the test will not fail, although I'd expect it to.

    TEST_ASSERT_EQUAL_STRING("foo", "foo2");
    TEST_ASSERT_EQUAL_STRING("foo2", "foo");

**Comment by art-of-dom** [comment]
Testing this locally the logic seems fine since it will keep checking until both are the null terminator or unequal. These test cases both fail as expected and I'm doing a pull request to explicitly show this test case.

**Comment by dueringa** [comment]
Sorry, my bad. I don't know what I tested on Friday that failed, but using the test code I provided, the test fails as expected.
