### ISSUE TITLE
Reinitialize project with every new test function

### ISSUE THREAD

**Issue by glenntws** [ThrowTheSwitch/Unity#411]
We are using Unity as part of Ceedling to test complex modules.

These modules often don't setup every private variable in their "Initialize" method or sometimes don't even feature a Initialization method.

Of course, resetting all the variables in the setUp function is possible, but when working with tons of private data types inside the module under test, this isn't comfortable at all. Including the source code file of the module under test is possible I think, but it's really not what we want to do, especially since we try to use Ceedling (Unity) as a Black-Box-Testing Tool.

Is there a setting or function we oversaw, which fulfills our needs? If not, is this a possible feature to add?

**Comment by mvandervoord** [comment]
Interesting problem! Thanks for bringing it up.

I don't believe there is an automatic way to make this happen. There isn't a platform-independent way that variables are initialized in C, and there isn't a way for us to fetch which variables would need to be reset on startup. This is something that could probably be added a compiler at a time, but (so far anyway) we've avoided most features which are specific to a single toolchain.

There are a couple of workarounds I'd consider, neither of which is ideal, but you can consider them and see if they fit your needs.

1. You could ADD an init function to your release module, even if it doesn't get called in your real source... or you could switch to using it in your release code also. An init function takes slightly longer than C takes to init your variables on startup, but not terribly so... plus it's self documenting.

2. You could break tests into multiple files. Each file will be compiling as its own module and therefore will automatically be running through your full C module variable init sequence.

Like I said, neither is ideal. If anyone else has ideas on this, please add them... both as workarounds or as how we might approach this as a real fix.

**Comment by glenntws** [comment]
Thanks for your fast answer. I know what you mean and I fully appreciate the compiler-universal structure of Unity.

I have a suggestion on how the problem could be fixed:

1. create a temporary code of the module under test
2. analyze the code for declaration of variables outside of functions
3. check every used type of the variable declarations for custom definitions inside the source code and all included header files (custom struct typedef, or just using "struct blabla = {}" with blabla being a defined struct)
4. IMPORTANT: recursive search is important. many people (for example our team) use structs inside structs, so going recursive until every reference is solved is important. 
5. generate a function inside the temporary copied module under test which assigns the default values (if given in the original defintion or in the struct/union typedef) or NULL_PTR / 0 to all those variables.

I think the most critical part is the recursive search inside structs and that this for sure is not that easy, but activating such a feature in unity/ceedling with a parameter in the config would be very cool i think.

**Comment by Letme** [comment]
I will assume you are using gcc? 

Otherwise some compilers have the flag to do so (for example IBM AIX xlc) and this seems like most reasonable job for a compiler, because it has all the data required. Exactly recursiveness will pose a problem as well how to extract these local variables with some external tool?

**Comment by glenntws** [comment]
> 
> 
> I will assume you are using gcc?
> 
> Otherwise some compilers have the flag to do so (for example IBM AIX xlc) and this seems like most reasonable job for a compiler, because it has all the data required. Exactly recursiveness will pose a problem as well how to extract these local variables with some external tool?

Yes, we are using gcc to natively test our modules on the development workstation.

I found a easy fix, which I think can be implemented into unity or a helper script (ceedling?) without much trouble.

Find every private variable in the code, copy those defintions and reinsert them with a suffix (something like "_reset_var") and as static const. Now, in a automatically generated function which get's called between every test, the real variables get assigned the value of the "_reset_var" variables.

The compiler handles all the memory problems, while this makes it easy for us. I think there is a bit more memory consumption since the variables are declared twice, but making this a configurable behaviour, this shouldn't be a problem, since most tests are run natively and not on the target.

**Comment by Letme** [comment]
How do you find every private variable in code? Do you intend to parse C sources and headers? That usually means that we need to use something after preprocessor to get uniform style out (CMock already shows big negative signs of regex parsing).

**Comment by glenntws** [comment]
parsing after preprocessor would be good, because ifdef's would already be checked. However, I don't know, how this should work and how far the negative experience with regex goes. Basically, every instruction (between ;'s) shall be checked for "<type> <variable name>" or "<type> <variable name> = ....".

**Comment by mvandervoord** [comment]
This is a good feature to add to Ceedling, but it doesn't make sense to add it directly to Unity. I'm closing this issue here and opening one on Ceedling to match.
