### ISSUE TITLE
Pointer comparison fails on TI C55x

### ISSUE THREAD

**Issue by detly** [ThrowTheSwitch/Unity#420]
On the TI C55x using their CGT compiler, pointer widths are 23 bits, whereas `int`s and `char`s are 16 bits. So `sizeof(int *)` is 2, and the pointer gets truncated to 16 bits in `UnityNumToPtr()`'s `case 2:`.

My previous PR for this had a fix, but it's no longer compatible with what was in PR #403 , and I can't see another way to resolve it.

(Note that `UnityNumToPtr()` is *always* going to be using the wrong size for such a platform eg. `UNITY_TEST_ASSERT_EACH_EQUAL_INT16()` will call `UnityNumToPtr(expected, 2)` when the real size is 1. But the pointer case is the only case where the incorrect size is too small rather than too big.)

**Comment by farrrb** [comment]
Can you provide a fully featured example code? 

UnityNumToPtr() shouldn't truncate the pointer at all, only the expected value should be truncated (upper bits). You put a 32 (or 64-bit) UNITY_INT into the function and get a pointer to the truncated version in the quick compare structure as a result. Am I missing something?

**Comment by detly** [comment]
The example code is just Unity's own unit test:

```text
tests/testunity.c:4623:testEqualPtrEachEqual:FAIL: Element 0 Expected 0x71FC0000 Was 0x000171FC: [[[[ Test Should Have Passed But Did Not ]]]]
```

The test is:

```c
void testEqualPtrEachEqual(void)
{
    char A = 1;
    char B = 2;
    char C = 3;
    char* p0[] = {&A, &A, &A};
    char* p1[] = {&A, &B, &C, &A};
    char* p2[] = {&B, &B};
    char* p3[] = {&C};

    TEST_ASSERT_EACH_EQUAL_PTR(&A, p0, 1);
    TEST_ASSERT_EACH_EQUAL_PTR(&A, p0, 3);
    TEST_ASSERT_EACH_EQUAL_PTR(&A, p1, 1);
    TEST_ASSERT_EACH_EQUAL_PTR(&B, p2, 2);
    TEST_ASSERT_EACH_EQUAL_PTR(&C, p3, 1);
}
```

`TEST_ASSERT_EACH_EQUAL_PTR(expected, actual, num_elements)` results in a call to `UnityNumToPtr((UNITY_PTR_TO_INT) (expected), sizeof(int*))`. In my build system I have set `UNITY_POINTER_WIDTH` to 23, so `UNITY_PTR_TO_INT` resolves to `UNITY_INT32`, so that should be fine. But `sizeof(int *)` is 2, so in `UnityNumToPtr()` we have:

```c
UNITY_INTERNAL_PTR UnityNumToPtr(
    const UNITY_INT num /* the pointer */,
    const UNITY_UINT8 size /* 2 */)
{
    switch(size) /* 2 */
    {
        /* ... */
        case 2:
            UnityQuickCompare.i16 = (UNITY_INT16)num;
            return (UNITY_INTERNAL_PTR)(&UnityQuickCompare.i16);
```

So despite requiring a 32 bit `int` to hold its value, it's going into a 16 bit field.

**Comment by farrrb** [comment]
Ah I see, I think you've successfully identified the culprit :) Imho we should change the sizeof(int*)) in `TEST_ASSERT_EACH_EQUAL_PTR(...)` to some kind of derivative from `UNITY_POINTER_WIDTH` (with rounding). My first thought would be something like `(UNITY_POINTER_WIDTH / 8)` to get the correct amount in bytes. This of course works only correct if it is a power of two.

What is your value for `UNITY_POINTER_WIDTH`? Is it **23 bit** or does Unity set it to the **next power of two** (as it should)? On our TMS320F281x the value is auto-detected and set to 32-bit.

**Comment by farrrb** [comment]
I started working on the fixes in my branch: https://github.com/farrrb/Unity/tree/fix-ti-c55-sizeof feel free to take a look at it and test it.

**Comment by detly** [comment]
My value for `UNITY_POINTER_WIDTH` is 23, but that's only because the [configuration docs](https://github.com/ThrowTheSwitch/Unity/blob/master/docs/UnityConfigurationGuide.md#unity_pointer_width) say to do that. Changing that "interface" should also imply a corresponding doc change, but I'm fine with that.

**Comment by mvandervoord** [comment]
Replaced by #425
