### ISSUE TITLE
Unity test testHexPrintsUpToMaxNumberOfNibbles() fails on TI C55x

### ISSUE THREAD

**Issue by detly** [ThrowTheSwitch/Unity#421]
This is the test:

```c
void testHexPrintsUpToMaxNumberOfNibbles(void)
{
#ifndef USING_OUTPUT_SPY
    TEST_IGNORE();
#else
    startPutcharSpy();
    UnityPrintNumberHex(0xBEE, 21);
    endPutcharSpy();
    TEST_ASSERT_EQUAL_INT(sizeof(UNITY_INT)*2, strlen(getBufferPutcharSpy()));
#endif
}
```

On TI, we have:

* `UNITY_MAX_NIBBLES == 8`
* `UNITY_INT_WIDTH == 16`
* `sizeof(UNITY_INT) == 1`
* actual `strlen`: 8
* expected: 4

So, fail.

For comparison, on an amd64 PC we have:

* `UNITY_MAX_NIBBLES == 16`
* `UNITY_INT_WIDTH == 64`
* `sizeof(UNITY_INT) == 8`
* actual `strlen`: 16
* expected: 16

Pass.

I cannot figure out how to make this test pass consistently on all platforms without introducing a dependency on `CHAR_BIT` ie. `limits.h`.

**Comment by detly** [comment]
Possible alternatives:

- simply have the expected value be `UNITY_MAX_NIBBLES`, although I'm not sure how useful a test that is (you'd almost just be checking that the preprocessor does division).

- add a case for `UNITY_MAX_NIBBLES` to be 4 on platforms like this, or just `UNITY_INT_WIDTH/4` in general.

**Comment by farrrb** [comment]
UNITY_INT should be at least 32-bit wide on all platforms. 

https://github.com/ThrowTheSwitch/Unity/blob/c9b1d217fd0cb26929d3554da1377e90aa583198/src/unity_internals.h#L131-L132

https://github.com/ThrowTheSwitch/Unity/blob/c9b1d217fd0cb26929d3554da1377e90aa583198/src/unity_internals.h#L145-L146

So my question is:
Isn't that the case for the TI C55x? So **sizeof**(UNITY_INT) should be **2** in your example (correct me please if I'm wrong). And in that case I would expect **8** for **UNITY_MAX_NIBBLES**. 

Please correct me if I'm not getting everything.

Imho the test is a good idea, but I would prefer changing the line to:
```C
void testHexPrintsUpToMaxNumberOfNibbles(void)
{
#ifndef USING_OUTPUT_SPY
    TEST_IGNORE();
#else
    startPutcharSpy();
    UnityPrintNumberHex(0xBEE, 21);
    endPutcharSpy();
#ifdef UNITY_SUPPORT_64
    TEST_ASSERT_EQUAL_INT(16, strlen(getBufferPutcharSpy()));
#else
    TEST_ASSERT_EQUAL_INT( 8, strlen(getBufferPutcharSpy()));
#endif
#endif
}
```

**Comment by farrrb** [comment]
Just for completeness here are the types based on [spru281g.pdf](http://www.ti.com/lit/ug/spru281g/spru281g.pdf)

![image](https://user-images.githubusercontent.com/4279710/57452325-cc835a80-7263-11e9-80aa-5f477a4e3252.png)

**Comment by farrrb** [comment]
I think we have a lot of other problems here with this DSP when you take a close look at **(unsigned) long long** ...

**Comment by detly** [comment]
Ah yep, I misread the macros. Should have pasted the failure message:

```text
tests/testunity.c:5760:testHexPrintsUpToMaxNumberOfNibbles:FAIL: Expected 4 Was 8: [[[[ Test Should Have Passed But Did Not ]]]]
```

So my table above was wrong. I quite like your solution, I don't always think it's wise to have calculations done in the unit test itself.

**Comment by detly** [comment]
> I think we have a lot of other problems here with this DSP when you take a close look at **(unsigned) long long** ...

Business as usual for DSPs :grimacing: — the 40 bit types are only available as specialised accumulator registers for the built in multiply-and-accumulate instructions, accessible via assembly or compiler intrinsics. The type exists so you can write C declarations for those intrinsics or assembly functions, it's not really expected that a programmer would declare a bunch on the stack or in an aggregate type.

**Comment by farrrb** [comment]
I refactored the test and startet working on a fix for all TI C55x issues in my branch: https://github.com/farrrb/Unity/tree/fix-ti-c55-sizeof

**Comment by detly** [comment]
Happy to run the tests on my C55x board when you're ready.

**Comment by mvandervoord** [comment]
Replaced by #425
