### ISSUE TITLE
New (minor) release

### ISSUE THREAD

**Issue by EwoutH** [ThrowTheSwitch/Unity#424]
The current release ([v2.4.3](https://github.com/ThrowTheSwitch/Unity/releases/tag/v2.4.3)) is 139 commits behind the master branch, when is the next (minor) release planned?

**Comment by mvandervoord** [comment]
Two weeks ago. ;)

Some of the recent merges have broken some things that I'm trying to work through first.

**Comment by dpostorivo** [comment]
@mvandervoord mind posting bugs for the broken items in the issues section?  There's a lot of interest in a new Unity/CMock/Ceedling release and a lot of the community would be happy to help

**Comment by dpostorivo** [comment]
I've noticed that   #377 (d700478) seems to cause some instability with ceedling due to `UNITY_EXEC_TIME_START' and `UNITY_EXEC_TIME_STOP' being in the test runner now. If those are commented out in the runner generations script, tests seem to work.

**Comment by dpostorivo** [comment]
After review again on a clean environment, I can't reproduce the issue I had with #377 . I'm assuming I had a stale unity_internal.h somewhere when building.

**Comment by mvandervoord** [comment]
I'm glad to hear that. I was just playing with that right now and couldn't make a problem happen with it.

**Comment by petermbauer** [comment]
Hi,

any updates regarding a release?

thx,
Peter
