### ISSUE TITLE
Test for infinite loops

### ISSUE THREAD

**Issue by korigod** [ThrowTheSwitch/Unity#434]
Now if the code under test contains an infinite loop, Unity just hangs. Is it possible to force some kind of timeout? Is there a proper way to test code for infinite loops or, broadly speaking, it's performance?

This problem was discussed in 2012, but it looks like this feature is still absent: https://github.com/ThrowTheSwitch/Ceedling/issues/16.

**Comment by Letme** [comment]
I dont think you are approaching the problem correctly. Infinte loop I usually ifdef out with precompiler, but that should be just 1 infinite loop (or maybe two) in whole code. You know where they are so you might as well design your unit tests around those functions (hint mock them).

**Comment by korigod** [comment]
I'm not talking about by-design loops, like in RTOS tasks, I mean when due to a mistake in some cases the unit under test enters an indefinite loop. In this case the test suite just halts.

**Comment by rajdeepbharati** [comment]
@korigod do you mean a deadlock?

**Comment by korigod** [comment]
@rajdeepbharati, deadlocks too — if the unit under test cause a deadlock, Unity just hangs.

**Comment by mvandervoord** [comment]
There's not really a platform independent way to handle this. If we tackle this issue at some point, it's going to be in Ceedling, where we can perform operations on the simulator or environment in order to force-stop execution.
