### ISSUE TITLE
Version information in source?

### ISSUE THREAD

**Issue by wolf99** [ThrowTheSwitch/Unity#436]
Can we have some release version information present somewhere in the source?

I contribute to a repo (https://github.com/exercism/c) that houses many C projects, each of which use Unity. Each project is created at a different time and it can be hard to know what version of Unity the contributor has used (some contributors download a release it direct from Github each time, some have cloned the repo and some just copy it from projects that already exist within the repo).

We have documented the version in use, but this isn't always noticed or followed and currently we have no easy way of discerning if it has been or not.

If the release version was documented somewhere parsable within the source files or as some kind of `#define` it would make maintenance a lot easier for us 😃 (could possibly even check it in our CI 🤔 )

(I imagine and hope there would be other use cases for this also!)

PS: I see there is a `version.info` file these days, trouble is that only the `src` directory is commonly included in projects. However, if it is there it is probably possible to automate updating the source version info whenever the `version.info` file gets changed

**Comment by mvandervoord** [comment]
This is a good thought. I will make it so. :)

**Comment by wolf99** [comment]
🙌
