### ISSUE TITLE
How to import VTK/ActiViz dlls to Unity?

### ISSUE THREAD

**Issue by anranx** [ThrowTheSwitch/Unity#444]
Hi! I have a problem about how to use VTK in Unity.
I put all the ActiViz dlls to Unity Assert/Plugins file, but unity has many same errors: DllNotFoundException: Kitware.VTK.vtkCommon.Unmanaged.dll. When I check this dll in Plugins file, this dll is already in there. I am using Unity2018.4.0f1+Activiz 5.8
I find some link about the same issue, but it seems to be no concrete solution.
https://github.com/ufz-vislab/VtkUnity/issues/5#issuecomment-531664278
https://stackoverflow.com/questions/56562718/how-to-import-the-kitware-vtk-dll-from-activiz-to-unity?r=SearchResults
So how to import VTK/ActiViz dlls to Unity? Thank you very much if someone can answer me.

**Comment by mvandervoord** [comment]
You're leaving a message on the wrong Unity project. This is Unity the test framework, not Unity 3D the game engine.
