### ISSUE TITLE
unity_malloc() doesn't enforce any minimum alignment

### ISSUE THREAD

**Issue by alecoding** [ThrowTheSwitch/Unity#447]
unity_malloc() doesn't make any assumption on the pointer alignment, de facto preventing its use on larger than 32-bit wide pointers.  

You can easily reproduce this problem by allocating two 16 bytes  blocks.  It is guarantee that the second allocation will not be a multiple of 8, this is not desirable on a 64-bit platform.

Maybe Unity could leverage use the recently introduced UNITY_POINTER_WIDTH define to do the upper rounding.

**Comment by mvandervoord** [comment]
UNITY_MALLOC_ALIGNMENT is already in effect. It's based on UNITY_POINTER_WIDTH.
