### ISSUE TITLE
examples makefile fail in Ubuntu

### ISSUE THREAD

**Issue by parrotrueper** [ThrowTheSwitch/Unity#452]
example_1 makefile:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

makefile:57: recipe for target 'default' failed
make: [default] Error 2 (ignored)

example_2 makefile:
makefile:63: recipe for target 'default' failed
make: [default] Error 2 (ignored)

**Comment by mvandervoord** [comment]
I can't reproduce this problem. To make this happen, did you clone the entire unity project and then execute the makefiles form the example directory? Do the self-tests pass?

**Comment by parrotrueper** [comment]
Yes I did.

However once you tweak the code so that the tests pass then the makefile is
happy.

**Comment by mvandervoord** [comment]
Oh! I see. Thanks for the valuable bit of information! The version of make you are using is returning an error because of the FAILURES and it is keeping the rest of the output from happening. I can fix it so that this won't be a problem on any version.

Thanks for the clarification!

**Comment by parrotrueper** [comment]
You are welcome
