### ISSUE TITLE
Discussion: verifyTest() and Ignore/Callback

### ISSUE THREAD

**Issue by jlindgren90** [ThrowTheSwitch/Unity#457]
At my work, we've been making use of UnityRunner_Verify() (which is a rename of CMock_Verify()) in some of our longer tests for a while now.  I'd like to get support for this usage merged upstream in some form.

The new verifyTest() function comes *so* close.  The only problem is that it's still not completely equivalent to UnityRunner_Verify() because it also calls CMock_Destroy() and CMock_Init().  As a result, it wipes out any Ignores and Callbacks that have been set up.

We have a number of tests that do the following:

1. Set up some Ignores and/or Callbacks at the start of the test (or even in setUp())
2. Set up some Expects and then call the function under test
3. Call UnityRunner_Verify() and verify any relevant system state
4. Repeat from step 2

I would love to be able to just find-and-replace UnityRunner_Verify() with verifyTest() in these tests, and have them still work correctly.

Could we change the behavior of verifyTest() (which is still very new, so shouldn't have any other users relying on the current behavior yet) to only call CMock_Verify(), so that it leaves Ignores/Callbacks intact?  I can submit a pull request if this change is acceptable.

**Comment by mvandervoord** [comment]
Good thought. It IS called just verify, after all. I'm in agreement.
