### ISSUE TITLE
The makefile provided by the website does not seem to work as intended

### ISSUE THREAD

**Issue by Mat-R** [ThrowTheSwitch/Unity#464]
Hi,

I an trying Unity with a very simple example but something looks wrong.
I read this page [Building with Make](http://www.throwtheswitch.org/build/make) from the website and downloaded the provided [Makefile](http://www.throwtheswitch.org/s/makefile-4fbf).

I integrated the Makefile in a simple project, then run `make test` but the output indicates the following:
> make: *** No rule to make target 'build/results/Test_abc.txt', needed by 'test'.  Stop.

However, if I run manually a command in the terminal `gcc src/abc.c test/Test_abc.c unity/src/unity.c -Iunity/src/ -Isrc/ -o test_abc.out`, I got the output I expect:

> ./test_abc.out 
> test/Test_abc.c:21:test_my_fun:PASS
>
> -----------------------
> 1 Tests 0 Failures 0 Ignored 
> OK

In the root of my project directory, I have:

- a src folder with abc.c and abc.h,
- a test folder with Test_abc.c,
- a unity folder which is the cloned git repository of Unity.

Here are my source files:
abc.c
``` c
#include "abc.h"

int my_fun(void) {
    return 1;
}
```
abc.h
``` c
#ifndef ABC_H
#define ABC_H

int my_fun(void);

#endif
```
Test_abc.c
``` c
#include "unity.h"
#include "abc.h"

void setUp(void)
{}

void tearDown(void)
{}

void test_my_fun(void) {
    TEST_ASSERT_TRUE(my_fun());
}

int main(void) {
    UNITY_BEGIN();
    RUN_TEST(test_my_fun);
    return UNITY_END();
}
```
Makefile (not modified)
``` Makefile
ifeq ($(OS),Windows_NT)
  ifeq ($(shell uname -s),) # not in a bash-like shell
	CLEANUP = del /F /Q
	MKDIR = mkdir
  else # in a bash-like shell, like msys
	CLEANUP = rm -f
	MKDIR = mkdir -p
  endif
	TARGET_EXTENSION=.exe
else
	CLEANUP = rm -f
	MKDIR = mkdir -p
	TARGET_EXTENSION=out
endif

.PHONY: clean
.PHONY: test

PATHU = unity/src/
PATHS = src/
PATHT = test/
PATHB = build/
PATHD = build/depends/
PATHO = build/objs/
PATHR = build/results/

BUILD_PATHS = $(PATHB) $(PATHD) $(PATHO) $(PATHR)

SRCT = $(wildcard $(PATHT)*.c)

COMPILE=gcc -c
LINK=gcc
DEPEND=gcc -MM -MG -MF
CFLAGS=-I. -I$(PATHU) -I$(PATHS) -DTEST

RESULTS = $(patsubst $(PATHT)Test%.c,$(PATHR)Test%.txt,$(SRCT) )

PASSED = `grep -s PASS $(PATHR)*.txt`
FAIL = `grep -s FAIL $(PATHR)*.txt`
IGNORE = `grep -s IGNORE $(PATHR)*.txt`

test: $(BUILD_PATHS) $(RESULTS)
	@echo "-----------------------\nIGNORES:\n-----------------------"
	@echo "$(IGNORE)"
	@echo "-----------------------\nFAILURES:\n-----------------------"
	@echo "$(FAIL)"
	@echo "-----------------------\nPASSED:\n-----------------------"
	@echo "$(PASSED)"
	@echo "\nDONE"

$(PATHR)%.txt: $(PATHB)%.$(TARGET_EXTENSION)
	-./$< > $@ 2>&1

$(PATHB)Test%.$(TARGET_EXTENSION): $(PATHO)Test%.o $(PATHO)%.o $(PATHU)unity.o #$(PATHD)Test%.d
	$(LINK) -o $@ $^

$(PATHO)%.o:: $(PATHT)%.c
	$(COMPILE) $(CFLAGS) $< -o $@

$(PATHO)%.o:: $(PATHS)%.c
	$(COMPILE) $(CFLAGS) $< -o $@

$(PATHO)%.o:: $(PATHU)%.c $(PATHU)%.h
	$(COMPILE) $(CFLAGS) $< -o $@

$(PATHD)%.d:: $(PATHT)%.c
	$(DEPEND) $@ $<

$(PATHB):
	$(MKDIR) $(PATHB)

$(PATHD):
	$(MKDIR) $(PATHD)

$(PATHO):
	$(MKDIR) $(PATHO)

$(PATHR):
	$(MKDIR) $(PATHR)

clean:
	$(CLEANUP) $(PATHO)*.o
	$(CLEANUP) $(PATHB)*.$(TARGET_EXTENSION)
	$(CLEANUP) $(PATHR)*.txt

.PRECIOUS: $(PATHB)Test%.$(TARGET_EXTENSION)
.PRECIOUS: $(PATHD)%.d
.PRECIOUS: $(PATHO)%.o
.PRECIOUS: $(PATHR)%.txt
```
Am I doing something wrong regarding the Makefile? Or did I miss something?

**Comment by Matthew-Allen** [comment]
I encountered this same situation. I'm still getting up to speed with make, but as I understand it the issue you're facing arises from the fact that the makefile as presented on the site expects the testing .c files to be named in such a way as to match the form Test$(FILE_TO_TEST).c due to the way the linking rule is set up.
``` makefile
$(PATHB)Test%.$(TARGET_EXTENSION): $(PATHO)Test%.o $(PATHO)%.o $(PATHU)unity.o #$(PATHD)Test%.d
	$(LINK) -o $@ $^
```
Specifically this bit:
``` makefile 
$(PATHO)Test%.o $(PATHO)%.o
```
In your case, it's because you've named your test file Test_abc.c. It should work if you name it Testabc.c instead.

**Comment by Mat-R** [comment]
Well spotted. Indeed I just messed with the test file names. Thanks!

**Comment by ghenry** [comment]
Hi all,

I'm getting the same as this issue, but I think it's because I have my [Makefile](https://static1.squarespace.com/static/54ed1e8de4b0a0f14fa7d0df/t/5bdae6744ae237cd89f5b9df/1541072591094/makefile-4fbf) in my test folder. I'm using autotools and don't want a Makefile in the root. If I do manually like:

```
localhost ~/src/sentrypeer/test [main*]$ gcc ../src/utils.c ../test/TestEventTimeStamp.c ../unity/src/unity.c -I../unity/src/ -I../src/ -o test_abc.out
localhost ~/src/sentrypeer/test [main*]$ ./test_abc.out 
../test/TestEventTimeStamp.c:13:test_event_timestamp:IGNORE: Hello world!

-----------------------
1 Tests 0 Failures 1 Ignored 
OK
```

all OK.  All I've done is put my Makefile in `test/` and updated the paths like so:

```
PATHU = ../unity/src/
PATHS = ../src/
PATHT = ../test/
PATHB = ../build/
PATHD = ../build/depends/
PATHO = ../build/objs/
PATHR = ../build/results/
```

Or should we use the example [Makefile](https://github.com/ThrowTheSwitch/Unity/blob/master/examples/example_1/makefile)?

Thanks.

**Comment by ghenry** [comment]
I also changed the echo lines to:

```
test: $(BUILD_PATHS) $(RESULTS)
	@echo -e "-----------------------\nIGNORES:\n-----------------------"
	@echo -e  "$(IGNORE)"
	@echo -e  "-----------------------\nFAILURES:\n-----------------------"
	@echo -e  "$(FAIL)"
	@echo -e  "-----------------------\nPASSED:\n-----------------------"
	@echo -e  "$(PASSED)"
	@echo -e "\nDONE."
```
