### ISSUE TITLE
Configuration options setup_name and teardown_name may be broken.

### ISSUE THREAD

**Issue by jvcdk** [ThrowTheSwitch/Unity#466]
Hi,

I have a unit test project using Unity (through Ceedling). I have a naming convention that functions start with a capitalised letter and it works nicely with the configuration option `test_prefix`.

Unfortunately, it seems that the configuration options `setup_name` and `teardown_name`. More specifically, when I try to set `setup_name` I get the following compile error:
```
/usr/local/ceedling/current/vendor/unity/src/unity.c:1812: undefined reference to `setUp'
```

Looking at the file this makes sense as the `setUp()` and `tearDown()` are called directly from within `UnityDefaultTestRun(...)`. See https://github.com/ThrowTheSwitch/Unity/blob/master/src/unity.c#L1812.

I am unsure on how to correct this; I have never worked with Ruby and I am in doubt on how to solve this issue in the first place; I guess a solution need to fit in to the pre-processing scripts, generating (boilerplate) code from configuration options etc.

Related issue: I think this feature was introduced in [configurable names for setup and teardown in the runner generator](https://github.com/ThrowTheSwitch/Unity/issues/71).

~Jørn

**Comment by mvandervoord** [comment]
Ah, interesting. I see why it would be a problem. Ceedling is producing its own test runner, so it's not going to directly use the default runner that you see here... but the default test runner is still being BUILT, so it needs for those functions to exist.

I think I can best fix this by not including the default runner if they have specified their own runner.

**Comment by jvcdk** [comment]
> I think I can best fix this by not including the default runner if they have specified their own runner.
Well... If I understand it correctly, this only works if a given project is building its own test runner (like Ceedling apparently does).

> Ceedling is producing its own test runner
I was unsure whether that was the case until now. I see you are active in the Ceedling project as well. Will you handle the issue there as well, or should I create an issue in that project as well?

~Jørn

**Comment by mvandervoord** [comment]
> Well... If I understand it correctly, this only works if a given project is building its own test runner (like Ceedling apparently does).

Correct. But if they are NOT generating their own runner, then they are also not changing the name of setUp and tearDown, so I believe this will work fine.

> I was unsure whether that was the case until now. I see you are active in the Ceedling project as well. Will you handle the issue there as well, or should I create an issue in that project as well?

It'll be automatic. The latest version of Unity is included with each release of Ceedling and the fix will automatically get pulled in. :)

**Comment by jvcdk** [comment]
> Correct. But if they are NOT generating their own runner, then they are also not changing the name of setUp and tearDown, so I believe this will work fine.

Strictly speaking, they might - correct?

I mean... If I use Unity without Ceedling, I will be using Unity's default runner. The configuration item `setup_name` is located within Unity, so I can still configure my setup to use custom set-up and tear-down function names, correct?

If so, then in this case your proposed solution will include the default test runner (from Unity) which do not take in to account `setup_name` and `teardown_name`.

> It'll be automatic. The latest version of Unity is included with each release of Ceedling and the fix will automatically get pulled in. :)

I just see now that the Unity test runner *does* use `setup_name` and `teardown_name`. I failed to look that up before now (just assumed that it did not).

**Comment by mvandervoord** [comment]
The setup_name and teardown_name configuration options only exist in the test runner generator script, which is generating a new test runner. So we're good. :)

**Comment by mvandervoord** [comment]
Alrighty. These changes are committed. Thanks for the help!

**Comment by jvcdk** [comment]
Hi Mark,

Now I had some time to look at this code. Two questions come to mind:

### 1) The need to define RUN_TEST

I pulled the latest code and renamed setup_name and teardown_name, expecting it just to work. It didn't. I had to also add the define RUN_TEST to make it work.

Question: Is this intentional? I was under the impression that Unity in collaboration with Ceedling would just figure this out?

### 2) Naming

Looking a bit at the code, you have two defines named, and from the sound of the names, here is my interpretation:

  * RUN_TEST: This should be / is defined when Unity should run tests.
  * UNITY_SKIP_DEFAULT_RUNNER: This should be / is defined when Unity should not include the default runner.

First of all, I am unsure why this is not just a single include, but then again; I have really not looked in to the code enough to know the details.

But... looking at the code we get this:
```C
#ifndef RUN_TEST
#define UNITY_SKIP_DEFAULT_RUNNER
void UnityDefaultTestRun(UnityTestFunction Func, const char* FuncName, const int FuncLineNum);
#endif
```

which seem to say:
  1. If run tests, then
  2. Set flag to skip default runner.
  3. Include declaration of default runner.

This seem wrong.

Later:
```C
#ifdef UNITY_SKIP_DEFAULT_RUNNER
void UnityDefaultTestRun(UnityTestFunction Func, const char* FuncName, const int FuncLineNum)
{
    ...
}
#endif
```

which seem to say:
  1. If Skip-runner is defined, then
  2. Here is the implementation.

Question: Is this correct?

I mean... things are working when I define RUN_TEST; I just thought it might be a (minor) error, hampering code reading for the next developer :)
