### ISSUE TITLE
Linker can't find UnityPrintFormatted

### ISSUE THREAD

**Issue by bigbrett** [ThrowTheSwitch/Unity#468]
I'm defining `UNITY_INCLUDE_PRINT_FORMATTED` in my test, but when I try to use `UnityPrintFormatted`, I get a linker error claiming: 

```
build/test/out/c/test_robot_bus_power.o: In function `test_robot_bus_power_current_scaling':
/home/brett/workspace/firmware/link-controller/test/robot/test_robot_bus_power.c:33: undefined reference to `UnityPrintFormatted'
collect2: error: ld returned 1 exit status
ERROR: Shell command failed.
> Shell executed command:
'gcc "build/test/out/c/test_robot_bus_power_runner.o" "build/test/out/c/test_robot_bus_power.o" "build/test/out/c/mock_robot_internal_adc.o" "build/test/out/c/unity.o" "build/test/out/c/robot_bus_power.o" "build/test/out/c/cmock.o" -o "build/test/out/te
st_robot_bus_power.out"'
> And exited with status: [1].


NOTICE: If the linker reports missing symbols, the following may be to blame:
  1. Test lacks #include statements corresponding to needed source files.
  2. Project search paths do not contain source files corresponding to #include statements in the test.
  3. Test does not #include needed mocks.

rake aborted!
```
I checked `unity.h` and it is most definitely there. 

I am using ceedling 0.29.0

**Comment by mvandervoord** [comment]
Hi. 

It's interesting that it's not running into this problem until it links. I assume you have the following in your project.yml file:

```
:defines:
  :test:
    - UNITY_INCLUDE_PRINT_FORMATTED
```

You've clobbered and rebuilt everything and it still has this issue?

**Comment by bigbrett** [comment]
damn I'm an idiot I thought `UNITY_INCLUDE_PRINT_FORMATTED` in the source file of the test itself. Guess this has to do with compilation order? 

Added it to project.yml and all is good. 

Might be worth throwing a tidbit in the docs about this for boneheads such as myself :) ?

**Comment by mvandervoord** [comment]
You're absolutely correct. It should be spelled out better in the documentation.

Each of the C files (Unity, the test runner, the test itself, etc) are built separately and then linked. By putting it in the test, it means the test will see a definition for UnityPrintFormatted in the header... but Unity itself was compiled without seeing that #define and therefore didn't create a UnityPrintFormatted. When it goes to link, you see the problem you ran into.

It's an easy mistake to make... particularly since it's not well spelled out.

**Comment by mvandervoord** [comment]
Fixed.

**Comment by denis-shienkov** [comment]
Hmmm:

> :defines:
>   :test:
>     - UNITY_INCLUDE_PRINT_FORMATTED

it does not work now: https://github.com/ThrowTheSwitch/Unity/issues/354
