### ISSUE TITLE
Unity crashes if cmock failure happens both in test case and tearDown

### ISSUE THREAD

**Issue by cy18** [ThrowTheSwitch/Unity#479]
Create a dummy.h, use this file as the source to generate mock_dummy.h .

    #ifndef DUMMY_H_
    #define DUMMY_H_
    
    extern void Func(void);

    #endif

Do test on following test file.

    // Test file
    #include "unity.h"
    #include "mock_dummy.h"
    void tearDown(void)
    {
        Func();
    }
    void Test_DoTest(void)
    {
        Func();
    }

The test would crash and generate empty output.

**Comment by mvandervoord** [comment]
I definitely get a failure, but not a crash. What method are you using to generate your test runner, or are you using the default RUN_TEST macro?

**Comment by cy18** [comment]
I'm using the master branch of cmock and unity. The runner is generated by lib/unity/auto/generate_test_runner.rb. It is as follows.

    /* AUTOGENERATED FILE. DO NOT EDIT. */
    
    /*=======Automagically Detected Files To Include=====*/
    #include "unity.h"
    #include "cmock.h"
    #include "mock_dummy.h"
    
    int GlobalExpectCount;
    int GlobalVerifyOrder;
    char* GlobalOrderError;
    
    /*=======External Functions This Runner Calls=====*/
    extern void setUp(void);
    extern void tearDown(void);
    extern void Test_DoTest(void);
    
    
    /*=======Mock Management=====*/
    static void CMock_Init(void)
    {
      GlobalExpectCount = 0;
      GlobalVerifyOrder = 0;
      GlobalOrderError = NULL;
      mock_dummy_Init();
    }
    static void CMock_Verify(void)
    {
      mock_dummy_Verify();
    }
    static void CMock_Destroy(void)
    {
      mock_dummy_Destroy();
    }
    
    /*=======Setup (stub)=====*/
    void setUp(void) {}
    
    /*=======Test Reset Options=====*/
    void resetTest(void);
    void resetTest(void)
    {
      tearDown();
      CMock_Verify();
      CMock_Destroy();
      CMock_Init();
      setUp();
    }
    void verifyTest(void);
    void verifyTest(void)
    {
      CMock_Verify();
    }
    /*=======Test Runner Used To Run Each Test=====*/
    static void run_test(UnityTestFunction func, const char* name, int line_num)
    {
        Unity.CurrentTestName = name;
        Unity.CurrentTestLineNumber = line_num;
    #ifdef UNITY_USE_COMMAND_LINE_ARGS
        if (!UnityTestMatches())
            return;
    #endif
        Unity.NumberOfTests++;
        UNITY_CLR_DETAILS();
        UNITY_EXEC_TIME_START();
        CMock_Init();
        if (TEST_PROTECT())
        {
    
                setUp();
                func();
    
        }
        if (TEST_PROTECT())
        {
            tearDown();
            CMock_Verify();
        }
        CMock_Destroy();
        UNITY_EXEC_TIME_STOP();
        UnityConcludeTest();
    }
    
    
    /*=======MAIN=====*/
    int main(void)
    {
      UnityBegin("tests/unity/test_unity2.c");
      run_test(Test_DoTest, "Test_DoTest", 8);
    
      CMock_Guts_MemFreeFinal();
      return UnityEnd();
    }


The script to generate mock is as follows. I added some plugins and changed the output path of mock.

	require "#{ENV['CMOCK_DIR']}/lib/cmock"
	
	raise "Header file to mock must be specified!" unless ARGV.length >= 1
	
	mock_out = ENV.fetch('MOCK_OUT', './build/mocks')+'/'+File.dirname(ARGV[0])
	cmock = CMock.new({
		:plugins =>[
			:ignore,
			:ignore_arg,
			:expect_any_args,
			:array,
			:callback,
			:return_thru_ptr,
		],
		:treat_externs => :include,
		:mock_prefix => 'mock_',
		:mock_path => mock_out,
		:callback_include_count => false,
		:enforce_strict_ordering => true,
	})
	cmock.setup_mocks(ARGV[0])

The generated mock is as follows.

    /* AUTOGENERATED FILE. DO NOT EDIT. */
    #include <string.h>
    #include <stdlib.h>
    #include <setjmp.h>
    #include "cmock.h"
    #include "mock_dummy.h"
    
    static const char* CMockString_Func = "Func";
    
    typedef struct _CMOCK_Func_CALL_INSTANCE
    {
      UNITY_LINE_TYPE LineNumber;
      int ExpectAnyArgsBool;
      int CallOrder;
    
    } CMOCK_Func_CALL_INSTANCE;
    
    static struct mock_dummyInstance
    {
      int Func_IgnoreBool;
      int Func_CallbackBool;
      CMOCK_Func_CALLBACK Func_CallbackFunctionPointer;
      int Func_CallbackCalls;
      CMOCK_MEM_INDEX_TYPE Func_CallInstance;
    } Mock;
    
    extern jmp_buf AbortFrame;
    extern int GlobalExpectCount;
    extern int GlobalVerifyOrder;
    
    void mock_dummy_Verify(void)
    {
      UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
      CMOCK_MEM_INDEX_TYPE call_instance;
      call_instance = Mock.Func_CallInstance;
      if (Mock.Func_IgnoreBool)
        call_instance = CMOCK_GUTS_NONE;
      UNITY_SET_DETAIL(CMockString_Func);
      UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == call_instance, cmock_line, CMockStringCalledLess);
      UNITY_CLR_DETAILS();
      if (Mock.Func_CallbackFunctionPointer != NULL)
        call_instance = CMOCK_GUTS_NONE;
    }
    
    void mock_dummy_Init(void)
    {
      mock_dummy_Destroy();
    }
    
    void mock_dummy_Destroy(void)
    {
      CMock_Guts_MemFreeAll();
      memset(&Mock, 0, sizeof(Mock));
      GlobalExpectCount = 0;
      GlobalVerifyOrder = 0;
    }
    
    void Func(void)
    {
      UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
      CMOCK_Func_CALL_INSTANCE* cmock_call_instance;
      UNITY_SET_DETAIL(CMockString_Func);
      cmock_call_instance = (CMOCK_Func_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Func_CallInstance);
      Mock.Func_CallInstance = CMock_Guts_MemNext(Mock.Func_CallInstance);
      if (Mock.Func_IgnoreBool)
      {
        UNITY_CLR_DETAILS();
        return;
      }
      if (!Mock.Func_CallbackBool &&
          Mock.Func_CallbackFunctionPointer != NULL)
      {
        Mock.Func_CallbackFunctionPointer();
        UNITY_CLR_DETAILS();
        return;
      }
      UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
      cmock_line = cmock_call_instance->LineNumber;
      if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
      if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
        UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
      if (Mock.Func_CallbackFunctionPointer != NULL)
      {
        Mock.Func_CallbackFunctionPointer();
      }
      UNITY_CLR_DETAILS();
    }
    
    void Func_CMockIgnore(void)
    {
      Mock.Func_IgnoreBool = (int)1;
    }
    
    void Func_CMockExpect(UNITY_LINE_TYPE cmock_line)
    {
      CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Func_CALL_INSTANCE));
      CMOCK_Func_CALL_INSTANCE* cmock_call_instance = (CMOCK_Func_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
      UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
      memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
      Mock.Func_CallInstance = CMock_Guts_MemChain(Mock.Func_CallInstance, cmock_guts_index);
      Mock.Func_IgnoreBool = (int)0;
      cmock_call_instance->LineNumber = cmock_line;
      cmock_call_instance->CallOrder = ++GlobalExpectCount;
      cmock_call_instance->ExpectAnyArgsBool = (int)0;
    }
    
    void Func_AddCallback(CMOCK_Func_CALLBACK Callback)
    {
      Mock.Func_IgnoreBool = (int)0;
      Mock.Func_CallbackBool = (int)1;
      Mock.Func_CallbackFunctionPointer = Callback;
    }
    
    void Func_Stub(CMOCK_Func_CALLBACK Callback)
    {
      Mock.Func_IgnoreBool = (int)0;
      Mock.Func_CallbackBool = (int)0;
      Mock.Func_CallbackFunctionPointer = Callback;
    }

**Comment by cy18** [comment]
@mvandervoord 

I may have found the problem.

The mock has following code:

      UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
      cmock_line = cmock_call_instance->LineNumber;

Since no Func_Expect() is called, cmock_call_instance is NULL, the test would fail and goes to 

https://github.com/ThrowTheSwitch/Unity/blob/622918a7df5336b555ffd8e525d14872f7a0e8fa/src/unity.c#L1739-L1745

The macro RETURN_IF_FAIL_OR_IGNORE expands to 

https://github.com/ThrowTheSwitch/Unity/blob/622918a7df5336b555ffd8e525d14872f7a0e8fa/src/unity.c#L22-L26

When first failure happens, the condition is not met, everything goes well. 

However, when the second failure happens, the Unity.CurrentTestFailed  is true and the function UnityFail would return directly.  It runs to 

    cmock_line = cmock_call_instance->LineNumber;

As cmock_call_instance is NULL, the program crashes. 

How about changing RETURN_IF_FAIL_OR_IGNORE  to the following macro to solve the problem.

    #define ABORT_IF_FAIL_OR_IGNORE if (Unity.CurrentTestFailed || Unity.CurrentTestIgnored) TEST_ABORT();

**Comment by mvandervoord** [comment]
Thanks @cy18 . Fixed!
