### ISSUE TITLE
Paths containing .h/.yaml/.yml interpreted as files by generate_test_runner.rb

### ISSUE THREAD

**Issue by petermbauer** [ThrowTheSwitch/Unity#480]
Since the regular expressions in https://github.com/ThrowTheSwitch/Unity/blob/master/auto/generate_test_runner.rb#L452 and https://github.com/ThrowTheSwitch/Unity/blob/master/auto/generate_test_runner.rb#L458 are too "liberal", paths to the output file containing .h/.yaml/.yml are interpreted as files so the default output filename is used instead.

Example for commandline argument path containing `.h`:
`generate_test_runner.rb default.yml test_mocked_TestM_Handler_Main.c C:/Jenkins/workspace/ler-set-wuccfg.hardfault_set-bit/build/test_mocked_TestM_Handler_Main_Runner.c`

**Comment by mvandervoord** [comment]
Thanks @petermbauer .

Fixed commit 371e062
