### ISSUE TITLE
Module Generator Naming Convention

### ISSUE THREAD

**Issue by seabrow** [ThrowTheSwitch/Unity#486]
The handling of naming option in the "Module Generator" does not seem to handle the "snake" option correctly.

In the project.yml file:
```
:module_generator:
 :naming: "snake"
```
When the following command is run = 
`ceedling module:create["my driver"]`

The following is created;

```
| - src:
|      | - my driver.c
|      | - my driver.h
|
| - test:
       | - test_my driver.c
```

It looks like it is basically ignored.

If I change the option to "caps":

```
:module_generator:
 :naming: "snake"
```

when I input the command = 
`ceedling module:create["my driver adc"]`

The following is created;
```
| - src:
|      | - MY DRIVER ADC.c
|      | - MY DRIVER ADC.h
|
| - test:
       | - test_MY DRIVER ADC.c
```

**Comment by mvandervoord** [comment]
Fixed
