### ISSUE TITLE
Can't compile tests with unity_fixture.h and current CMakeList.txt

### ISSUE THREAD

**Issue by ernestguillem** [ThrowTheSwitch/Unity#521]
Hi,
I'm trying to compile unity tests with the currently provided CMakeLists.txt and while it works when using unity.h if I use Grenning's approach using unity_fixture.h I get an error without modifying the list like this:

```
target_sources(${PROJECT_NAME}
    PRIVATE
        src/unity.c
        extras/fixture/src/unity_fixture.c
        extras/memory/src/unity_memory.c
)

target_include_directories(${PROJECT_NAME}
    PUBLIC
        $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/src>
        $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/extras/fixture/src>
        $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/extras/memory/src>
        $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}>
        $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}/${PROJECT_NAME}>
)
```

When I add the sources and the include directories I can compile using the two approaches. Would there be any drawbacks for anyone not using the fixture? Any chance of making a PR for this? Am I doing it completely wrong?

Thanks a lot in advance.

**Comment by gmircea** [comment]
I also think this is a required feature , otherwise is hard to use the optional add-on `fixture`. 
This could be disabled by default, and enabled in `CMakeLists.txt` with an `option`:
`option(WITH_FIXTURE "Use Unity Fixtures" OFF)`
