### ISSUE TITLE
test of Unity fails in test_unity_core.c

### ISSUE THREAD

**Issue by shintarokkk** [ThrowTheSwitch/Unity#529]
When I run "make test" in Unity/test, the test fails in test_unity_core.c and the following tests does not run.
<details>
<summary>terminal output</summary>
<pre>
gcc -std=c99 -pedantic -Wall -Wextra -Werror -Wno-switch-enum -Wno-double-promotion -Wbad-function-cast -Wcast-qual -Wold-style-definition -Wshadow -Wstrict-overflow -Wstrict-prototypes -Wswitch-default -Wundef  -D UNITY_OUTPUT_CHAR=putcharSpy -D UNITY_OUTPUT_CHAR_HEADER_DECLARATION=putcharSpy\(int\) -D UNITY_OUTPUT_FLUSH=flushSpy -D UNITY_OUTPUT_FLUSH_HEADER_DECLARATION=flushSpy\(void\) -D UNITY_SUPPORT_64 -D UNITY_INCLUDE_DOUBLE -I ../src ../src/unity.c tests/test_unity_arrays.c build/test_unity_arraysRunner.c -o build/testunity-cov.exe
./build/testunity-cov.exe
tests/test_unity_arrays.c:36:testInt64ArrayWithinDelta:PASS
tests/test_unity_arrays.c:50:testInt64ArrayWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:78:testInt64ArrayNotWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:92:testInt64ArrayWithinDeltaPointless:PASS
tests/test_unity_arrays.c:106:testInt64ArrayWithinDeltaPointlessAndMessage:PASS
tests/test_unity_arrays.c:120:testInt64ArrayWithinDeltaExpectedNull:PASS
tests/test_unity_arrays.c:133:testInt64ArrayWithinDeltaExpectedNullAndMessage:PASS
tests/test_unity_arrays.c:146:testInt64ArrayWithinDeltaActualNull:PASS
tests/test_unity_arrays.c:159:testInt64ArrayWithinDeltaActualNullAndMessage:PASS
tests/test_unity_arrays.c:172:testInt64ArrayWithinDeltaSamePointer:PASS
tests/test_unity_arrays.c:183:testInt64ArrayWithinDeltaSamePointerAndMessage:PASS
tests/test_unity_arrays.c:194:testIntArrayWithinDelta:PASS
tests/test_unity_arrays.c:204:testIntArrayWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:214:testIntArrayNotWithinDelta:PASS
tests/test_unity_arrays.c:224:testIntArrayNotWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:234:testIntArrayWithinDeltaPointless:PASS
tests/test_unity_arrays.c:244:testIntArrayWithinDeltaPointlessAndMessage:PASS
tests/test_unity_arrays.c:254:testIntArrayWithinDeltaExpectedNull:PASS
tests/test_unity_arrays.c:263:testIntArrayWithinDeltaExpectedNullAndMessage:PASS
tests/test_unity_arrays.c:272:testIntArrayWithinDeltaActualNull:PASS
tests/test_unity_arrays.c:281:testIntArrayWithinDeltaActualNullAndMessage:PASS
tests/test_unity_arrays.c:290:testIntArrayWithinDeltaSamePointer:PASS
tests/test_unity_arrays.c:297:testIntArrayWithinDeltaSamePointerAndMessage:PASS
tests/test_unity_arrays.c:304:testInt16ArrayWithinDelta:PASS
tests/test_unity_arrays.c:314:testInt16ArrayWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:324:testInt16ArrayNotWithinDelta:PASS
tests/test_unity_arrays.c:334:testInt16ArrayNotWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:344:testInt16ArrayWithinDeltaPointless:PASS
tests/test_unity_arrays.c:354:testInt16ArrayWithinDeltaPointlessAndMessage:PASS
tests/test_unity_arrays.c:364:testInt16ArrayWithinDeltaExpectedNull:PASS
tests/test_unity_arrays.c:373:testInt16ArrayWithinDeltaExpectedNullAndMessage:PASS
tests/test_unity_arrays.c:382:testInt16ArrayWithinDeltaActualNull:PASS
tests/test_unity_arrays.c:391:testInt16ArrayWithinDeltaActualNullAndMessage:PASS
tests/test_unity_arrays.c:400:testInt16ArrayWithinDeltaSamePointer:PASS
tests/test_unity_arrays.c:407:testInt16ArrayWithinDeltaSamePointerAndMessage:PASS
tests/test_unity_arrays.c:414:testInt8ArrayWithinDelta:PASS
tests/test_unity_arrays.c:424:testInt8ArrayWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:434:testInt8ArrayNotWithinDelta:PASS
tests/test_unity_arrays.c:444:testInt8ArrayNotWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:454:testInt8ArrayWithinDeltaPointless:PASS
tests/test_unity_arrays.c:464:testInt8ArrayWithinDeltaPointlessAndMessage:PASS
tests/test_unity_arrays.c:474:testInt8ArrayWithinDeltaExpectedNull:PASS
tests/test_unity_arrays.c:483:testInt8ArrayWithinDeltaExpectedNullAndMessage:PASS
tests/test_unity_arrays.c:492:testInt8ArrayWithinDeltaActualNull:PASS
tests/test_unity_arrays.c:501:testInt8ArrayWithinDeltaActualNullAndMessage:PASS
tests/test_unity_arrays.c:510:testInt8ArrayWithinDeltaSamePointer:PASS
tests/test_unity_arrays.c:517:testInt8ArrayWithinDeltaSamePointerAndMessage:PASS
tests/test_unity_arrays.c:524:testCHARArrayWithinDelta:PASS
tests/test_unity_arrays.c:534:testCHARArrayWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:544:testCHARArrayNotWithinDelta:PASS
tests/test_unity_arrays.c:554:testCHARArrayNotWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:564:testCHARArrayWithinDeltaPointless:PASS
tests/test_unity_arrays.c:574:testCHARArrayWithinDeltaPointlessAndMessage:PASS
tests/test_unity_arrays.c:584:testCHARArrayWithinDeltaExpectedNull:PASS
tests/test_unity_arrays.c:593:testCHARArrayWithinDeltaExpectedNullAndMessage:PASS
tests/test_unity_arrays.c:602:testCHARArrayWithinDeltaActualNull:PASS
tests/test_unity_arrays.c:611:testCHARArrayWithinDeltaActualNullAndMessage:PASS
tests/test_unity_arrays.c:620:testCHARArrayWithinDeltaSamePointer:PASS
tests/test_unity_arrays.c:627:testCHARArrayWithinDeltaSamePointerAndMessage:PASS
tests/test_unity_arrays.c:634:testUInt64ArrayWithinDelta:PASS
tests/test_unity_arrays.c:648:testUInt64ArrayWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:662:testUInt64ArrayNotWithinDelta:PASS
tests/test_unity_arrays.c:676:testUInt64ArrayNotWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:690:testUInt64ArrayWithinDeltaPointless:PASS
tests/test_unity_arrays.c:704:testUInt64ArrayWithinDeltaPointlessAndMessage:PASS
tests/test_unity_arrays.c:718:testUInt64ArrayWithinDeltaExpectedNull:PASS
tests/test_unity_arrays.c:731:testUInt64ArrayWithinDeltaExpectedNullAndMessage:PASS
tests/test_unity_arrays.c:744:testUInt64ArrayWithinDeltaActualNull:PASS
tests/test_unity_arrays.c:757:testUInt64ArrayWithinDeltaActualNullAndMessage:PASS
tests/test_unity_arrays.c:770:testUInt64ArrayWithinDeltaSamePointer:PASS
tests/test_unity_arrays.c:781:testUInt64ArrayWithinDeltaSamePointerAndMessage:PASS
tests/test_unity_arrays.c:792:testUIntArrayWithinDelta:PASS
tests/test_unity_arrays.c:802:testUIntArrayWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:812:testUIntArrayNotWithinDelta:PASS
tests/test_unity_arrays.c:822:testUIntArrayNotWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:832:testUIntArrayWithinDeltaPointless:PASS
tests/test_unity_arrays.c:842:testUIntArrayWithinDeltaPointlessAndMessage:PASS
tests/test_unity_arrays.c:852:testUIntArrayWithinDeltaExpectedNull:PASS
tests/test_unity_arrays.c:861:testUIntArrayWithinDeltaExpectedNullAndMessage:PASS
tests/test_unity_arrays.c:870:testUIntArrayWithinDeltaActualNull:PASS
tests/test_unity_arrays.c:879:testUIntArrayWithinDeltaActualNullAndMessage:PASS
tests/test_unity_arrays.c:888:testUIntArrayWithinDeltaSamePointer:PASS
tests/test_unity_arrays.c:895:testUIntArrayWithinDeltaSamePointerAndMessage:PASS
tests/test_unity_arrays.c:902:testUInt16ArrayWithinDelta:PASS
tests/test_unity_arrays.c:912:testUInt16ArrayWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:922:testUInt16ArrayNotWithinDelta:PASS
tests/test_unity_arrays.c:932:testUInt16ArrayNotWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:942:testUInt16ArrayWithinDeltaPointless:PASS
tests/test_unity_arrays.c:952:testUInt16ArrayWithinDeltaPointlessAndMessage:PASS
tests/test_unity_arrays.c:962:testUInt16ArrayWithinDeltaExpectedNull:PASS
tests/test_unity_arrays.c:971:testUInt16ArrayWithinDeltaExpectedNullAndMessage:PASS
tests/test_unity_arrays.c:980:testUInt16ArrayWithinDeltaActualNull:PASS
tests/test_unity_arrays.c:989:testUInt16ArrayWithinDeltaActualNullAndMessage:PASS
tests/test_unity_arrays.c:998:testUInt16ArrayWithinDeltaSamePointer:PASS
tests/test_unity_arrays.c:1005:testUInt16ArrayWithinDeltaSamePointerAndMessage:PASS
tests/test_unity_arrays.c:1012:testUInt8ArrayWithinDelta:PASS
tests/test_unity_arrays.c:1022:testUInt8ArrayWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:1032:testUInt8ArrayNotWithinDelta:PASS
tests/test_unity_arrays.c:1042:testUInt8ArrayNotWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:1052:testUInt8ArrayWithinDeltaPointless:PASS
tests/test_unity_arrays.c:1062:testUInt8ArrayWithinDeltaPointlessAndMessage:PASS
tests/test_unity_arrays.c:1072:testUInt8ArrayWithinDeltaExpectedNull:PASS
tests/test_unity_arrays.c:1081:testUInt8ArrayWithinDeltaExpectedNullAndMessage:PASS
tests/test_unity_arrays.c:1090:testUInt8ArrayWithinDeltaActualNull:PASS
tests/test_unity_arrays.c:1099:testUInt8ArrayWithinDeltaActualNullAndMessage:PASS
tests/test_unity_arrays.c:1108:testUInt8ArrayWithinDeltaSamePointer:PASS
tests/test_unity_arrays.c:1115:testUInt8ArrayWithinDeltaSamePointerAndMessage:PASS
tests/test_unity_arrays.c:1122:testHEX64ArrayWithinDelta:PASS
tests/test_unity_arrays.c:1136:testHEX64ArrayWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:1150:testHEX64ArrayNotWithinDelta:PASS
tests/test_unity_arrays.c:1164:testHEX64ArrayNotWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:1178:testHEX64ArrayWithinDeltaPointless:PASS
tests/test_unity_arrays.c:1192:testHEX64ArrayWithinDeltaPointlessAndMessage:PASS
tests/test_unity_arrays.c:1206:testHEX64ArrayWithinDeltaExpectedNull:PASS
tests/test_unity_arrays.c:1219:testHEX64ArrayWithinDeltaExpectedNullAndMessage:PASS
tests/test_unity_arrays.c:1232:testHEX64ArrayWithinDeltaActualNull:PASS
tests/test_unity_arrays.c:1245:testHEX64ArrayWithinDeltaActualNullAndMessage:PASS
tests/test_unity_arrays.c:1258:testHEX64ArrayWithinDeltaSamePointer:PASS
tests/test_unity_arrays.c:1269:testHEX64ArrayWithinDeltaSamePointerAndMessage:PASS
tests/test_unity_arrays.c:1280:testHEX32ArrayWithinDelta:PASS
tests/test_unity_arrays.c:1290:testHEX32ArrayWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:1300:testHEX32ArrayNotWithinDelta:PASS
tests/test_unity_arrays.c:1310:testHEX32ArrayNotWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:1320:testHEX32ArrayWithinDeltaPointless:PASS
tests/test_unity_arrays.c:1330:testHEX32ArrayWithinDeltaPointlessAndMessage:PASS
tests/test_unity_arrays.c:1340:testHEX32ArrayWithinDeltaExpectedNull:PASS
tests/test_unity_arrays.c:1349:testHEX32ArrayWithinDeltaExpectedNullAndMessage:PASS
tests/test_unity_arrays.c:1358:testHEX32ArrayWithinDeltaActualNull:PASS
tests/test_unity_arrays.c:1367:testHEX32ArrayWithinDeltaActualNullAndMessage:PASS
tests/test_unity_arrays.c:1376:testHEX32ArrayWithinDeltaSamePointer:PASS
tests/test_unity_arrays.c:1383:testHEX32ArrayWithinDeltaSamePointerAndMessage:PASS
tests/test_unity_arrays.c:1391:testHEX16ArrayWithinDelta:PASS
tests/test_unity_arrays.c:1401:testHEX16ArrayWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:1411:testHEX16ArrayNotWithinDelta:PASS
tests/test_unity_arrays.c:1421:testHEX16ArrayNotWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:1431:testHEX16ArrayWithinDeltaPointless:PASS
tests/test_unity_arrays.c:1441:testHEX16ArrayWithinDeltaPointlessAndMessage:PASS
tests/test_unity_arrays.c:1451:testHEX16ArrayWithinDeltaExpectedNull:PASS
tests/test_unity_arrays.c:1460:testHEX16ArrayWithinDeltaExpectedNullAndMessage:PASS
tests/test_unity_arrays.c:1469:testHEX16ArrayWithinDeltaActualNull:PASS
tests/test_unity_arrays.c:1478:testHEX16ArrayWithinDeltaActualNullAndMessage:PASS
tests/test_unity_arrays.c:1487:testHEX16ArrayWithinDeltaSamePointer:PASS
tests/test_unity_arrays.c:1494:testHEX16ArrayWithinDeltaSamePointerAndMessage:PASS
tests/test_unity_arrays.c:1501:testHEX8ArrayWithinDelta:PASS
tests/test_unity_arrays.c:1511:testHEX8ArrayWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:1521:testHEX8ArrayNotWithinDelta:PASS
tests/test_unity_arrays.c:1531:testHEX8ArrayNotWithinDeltaAndMessage:PASS
tests/test_unity_arrays.c:1541:testHEX8ArrayWithinDeltaPointless:PASS
tests/test_unity_arrays.c:1551:testHEX8ArrayWithinDeltaPointlessAndMessage:PASS
tests/test_unity_arrays.c:1561:testHEX8ArrayWithinDeltaExpectedNull:PASS
tests/test_unity_arrays.c:1570:testHEX8ArrayWithinDeltaExpectedNullAndMessage:PASS
tests/test_unity_arrays.c:1579:testHEX8ArrayWithinDeltaActualNull:PASS
tests/test_unity_arrays.c:1588:testHEX8ArrayWithinDeltaActualNullAndMessage:PASS
tests/test_unity_arrays.c:1597:testHEX8ArrayWithinDeltaSamePointer:PASS
tests/test_unity_arrays.c:1604:testHEX8ArrayWithinDeltaSamePointerAndMessage:PASS
tests/test_unity_arrays.c:1611:testEqualIntArrays:PASS
tests/test_unity_arrays.c:1626:testNotEqualIntArraysNullExpected:PASS
tests/test_unity_arrays.c:1636:testNotEqualIntArraysNullActual:PASS
tests/test_unity_arrays.c:1646:testNotEqualIntArrays1:PASS
tests/test_unity_arrays.c:1656:testNotEqualIntArrays2:PASS
tests/test_unity_arrays.c:1666:testNotEqualIntArrays3:PASS
tests/test_unity_arrays.c:1676:testNotEqualIntArraysLengthZero:PASS
tests/test_unity_arrays.c:1686:testEqualIntEachEqual:PASS
tests/test_unity_arrays.c:1700:testNotEqualIntEachEqualNullActual:PASS
tests/test_unity_arrays.c:1709:testNotEqualIntEachEqual1:PASS
tests/test_unity_arrays.c:1718:testNotEqualIntEachEqual2:PASS
tests/test_unity_arrays.c:1727:testNotEqualIntEachEqual3:PASS
tests/test_unity_arrays.c:1736:testNotEqualEachEqualLengthZero:PASS
tests/test_unity_arrays.c:1745:testEqualPtrArrays:PASS
tests/test_unity_arrays.c:1762:testNotEqualPtrArraysNullExpected:PASS
tests/test_unity_arrays.c:1774:testNotEqualPtrArraysNullActual:PASS
tests/test_unity_arrays.c:1786:testNotEqualPtrArrays1:PASS
tests/test_unity_arrays.c:1799:testNotEqualPtrArrays2:PASS
tests/test_unity_arrays.c:1812:testNotEqualPtrArrays3:PASS
tests/test_unity_arrays.c:1825:testEqualPtrEachEqual:PASS
tests/test_unity_arrays.c:1842:testNotEqualPtrEachEqualNullExpected:PASS
tests/test_unity_arrays.c:1853:testNotEqualPtrEachEqualNullActual:PASS
tests/test_unity_arrays.c:1863:testNotEqualPtrEachEqual1:PASS
tests/test_unity_arrays.c:1874:testNotEqualPtrEachEqual2:PASS
tests/test_unity_arrays.c:1885:testNotEqualPtrEachEqual3:PASS
tests/test_unity_arrays.c:1896:testEqualInt8Arrays:PASS
tests/test_unity_arrays.c:1910:testNotEqualInt8Arrays:PASS
tests/test_unity_arrays.c:1920:testEqualInt8EachEqual:PASS
tests/test_unity_arrays.c:1934:testNotEqualInt8EachEqual:PASS
tests/test_unity_arrays.c:1943:testEqualCHARArrays:PASS
tests/test_unity_arrays.c:1957:testNotEqualCHARArrays:PASS
tests/test_unity_arrays.c:1967:testEqualCHAREachEqual:PASS
tests/test_unity_arrays.c:1981:testNotEqualCHAREachEqual:PASS
tests/test_unity_arrays.c:1990:testEqualUIntArrays:PASS
tests/test_unity_arrays.c:2004:testNotEqualUIntArrays1:PASS
tests/test_unity_arrays.c:2014:testNotEqualUIntArrays2:PASS
tests/test_unity_arrays.c:2024:testNotEqualUIntArrays3:PASS
tests/test_unity_arrays.c:2034:testEqualUIntEachEqual:PASS
tests/test_unity_arrays.c:2048:testNotEqualUIntEachEqual1:PASS
tests/test_unity_arrays.c:2057:testNotEqualUIntEachEqual2:PASS
tests/test_unity_arrays.c:2066:testNotEqualUIntEachEqual3:PASS
tests/test_unity_arrays.c:2075:testEqualInt16Arrays:PASS
tests/test_unity_arrays.c:2089:testNotEqualInt16Arrays:PASS
tests/test_unity_arrays.c:2099:testEqualInt16EachEqual:PASS
tests/test_unity_arrays.c:2113:testNotEqualInt16EachEqual:PASS
tests/test_unity_arrays.c:2122:testEqualInt32Arrays:PASS
tests/test_unity_arrays.c:2136:testNotEqualInt32Arrays:PASS
tests/test_unity_arrays.c:2146:testEqualInt32EachEqual:PASS
tests/test_unity_arrays.c:2160:testNotEqualInt32EachEqual:PASS
tests/test_unity_arrays.c:2169:testEqualUINT8Arrays:PASS
tests/test_unity_arrays.c:2183:testNotEqualUINT8Arrays1:PASS
tests/test_unity_arrays.c:2193:testNotEqualUINT8Arrays2:PASS
tests/test_unity_arrays.c:2203:testNotEqualUINT8Arrays3:PASS
tests/test_unity_arrays.c:2214:testEqualUINT16Arrays:PASS
tests/test_unity_arrays.c:2228:testNotEqualUINT16Arrays1:PASS
tests/test_unity_arrays.c:2238:testNotEqualUINT16Arrays2:PASS
tests/test_unity_arrays.c:2248:testNotEqualUINT16Arrays3:PASS
tests/test_unity_arrays.c:2258:testEqualUINT32Arrays:PASS
tests/test_unity_arrays.c:2272:testNotEqualUINT32Arrays1:PASS
tests/test_unity_arrays.c:2282:testNotEqualUINT32Arrays2:PASS
tests/test_unity_arrays.c:2292:testNotEqualUINT32Arrays3:PASS
tests/test_unity_arrays.c:2302:testEqualHEXArrays:PASS
tests/test_unity_arrays.c:2316:testNotEqualHEXArrays1:PASS
tests/test_unity_arrays.c:2326:testNotEqualHEXArrays2:PASS
tests/test_unity_arrays.c:2336:testNotEqualHEXArrays3:PASS
tests/test_unity_arrays.c:2346:testEqualHEX32Arrays:PASS
tests/test_unity_arrays.c:2360:testNotEqualHEX32Arrays1:PASS
tests/test_unity_arrays.c:2370:testNotEqualHEX32Arrays2:PASS
tests/test_unity_arrays.c:2380:testNotEqualHEX32Arrays3:PASS
tests/test_unity_arrays.c:2390:testEqualHEX16Arrays:PASS
tests/test_unity_arrays.c:2404:testNotEqualHEX16Arrays1:PASS
tests/test_unity_arrays.c:2414:testNotEqualHEX16Arrays2:PASS
tests/test_unity_arrays.c:2424:testNotEqualHEX16Arrays3:PASS
tests/test_unity_arrays.c:2434:testEqualHEX8Arrays:PASS
tests/test_unity_arrays.c:2448:testNotEqualHEX8Arrays1:PASS
tests/test_unity_arrays.c:2458:testNotEqualHEX8Arrays2:PASS
tests/test_unity_arrays.c:2468:testNotEqualHEX8Arrays3:PASS
tests/test_unity_arrays.c:2478:testEqualUINT8EachEqual:PASS
tests/test_unity_arrays.c:2492:testNotEqualUINT8EachEqual1:PASS
tests/test_unity_arrays.c:2501:testNotEqualUINT8EachEqual2:PASS
tests/test_unity_arrays.c:2510:testNotEqualUINT8EachEqual3:PASS
tests/test_unity_arrays.c:2519:testEqualUINT16EachEqual:PASS
tests/test_unity_arrays.c:2533:testNotEqualUINT16EachEqual1:PASS
tests/test_unity_arrays.c:2542:testNotEqualUINT16EachEqual2:PASS
tests/test_unity_arrays.c:2551:testNotEqualUINT16EachEqual3:PASS
tests/test_unity_arrays.c:2560:testEqualUINT32EachEqual:PASS
tests/test_unity_arrays.c:2574:testNotEqualUINT32EachEqual1:PASS
tests/test_unity_arrays.c:2583:testNotEqualUINT32EachEqual2:PASS
tests/test_unity_arrays.c:2592:testNotEqualUINT32EachEqual3:PASS
tests/test_unity_arrays.c:2601:testEqualHEXEachEqual:PASS
tests/test_unity_arrays.c:2615:testNotEqualHEXEachEqual1:PASS
tests/test_unity_arrays.c:2624:testNotEqualHEXEachEqual2:PASS
tests/test_unity_arrays.c:2633:testNotEqualHEXEachEqual3:PASS
tests/test_unity_arrays.c:2642:testEqualHEX32EachEqual:PASS
tests/test_unity_arrays.c:2656:testNotEqualHEX32EachEqual1:PASS
tests/test_unity_arrays.c:2665:testNotEqualHEX32EachEqual2:PASS
tests/test_unity_arrays.c:2674:testNotEqualHEX32EachEqual3:PASS
tests/test_unity_arrays.c:2683:testEqualHEX16EachEqual:PASS
tests/test_unity_arrays.c:2697:testNotEqualHEX16EachEqual1:PASS
tests/test_unity_arrays.c:2706:testNotEqualHEX16EachEqual2:PASS
tests/test_unity_arrays.c:2715:testNotEqualHEX16EachEqual3:PASS
tests/test_unity_arrays.c:2724:testEqualHEX8EachEqual:PASS
tests/test_unity_arrays.c:2738:testNotEqualHEX8EachEqual1:PASS
tests/test_unity_arrays.c:2747:testNotEqualHEX8EachEqual2:PASS
tests/test_unity_arrays.c:2756:testNotEqualHEX8EachEqual3:PASS
tests/test_unity_arrays.c:2765:testEqualHEX64Arrays:PASS
tests/test_unity_arrays.c:2783:testEqualUint64Arrays:PASS
tests/test_unity_arrays.c:2801:testEqualInt64Arrays:PASS
tests/test_unity_arrays.c:2820:testNotEqualHEX64Arrays1:PASS
tests/test_unity_arrays.c:2834:testNotEqualHEX64Arrays2:PASS
tests/test_unity_arrays.c:2848:testNotEqualUint64Arrays:PASS
tests/test_unity_arrays.c:2862:testNotEqualInt64Arrays:PASS

-----------------------
267 Tests 0 Failures 0 Ignored 
OK
gcc -std=c99 -pedantic -Wall -Wextra -Werror -Wno-switch-enum -Wno-double-promotion -Wbad-function-cast -Wcast-qual -Wold-style-definition -Wshadow -Wstrict-overflow -Wstrict-prototypes -Wswitch-default -Wundef  -D UNITY_OUTPUT_CHAR=putcharSpy -D UNITY_OUTPUT_CHAR_HEADER_DECLARATION=putcharSpy\(int\) -D UNITY_OUTPUT_FLUSH=flushSpy -D UNITY_OUTPUT_FLUSH_HEADER_DECLARATION=flushSpy\(void\) -D UNITY_SUPPORT_64 -D UNITY_INCLUDE_DOUBLE -I ../src ../src/unity.c tests/test_unity_core.c build/test_unity_coreRunner.c -o build/testunity-cov.exe
./build/testunity-cov.exe
tests/test_unity_core.c:36:testUnitySizeInitializationReminder:PASS
tests/test_unity_core.c:94:testPassShouldEndImmediatelyWithPass:PASS
tests/test_unity_core.c:102:testPassShouldEndImmediatelyWithPassAndMessage:INFO: Woohoo! This Automatically Passes!
tests/test_unity_core.c:100:testPassShouldEndImmediatelyWithPassAndMessage:PASS
tests/test_unity_core.c:108:testMessageShouldDisplayMessageWithoutEndingAndGoOnToPass:INFO: This is just a message
tests/test_unity_core.c:109:testMessageShouldDisplayMessageWithoutEndingAndGoOnToPass:INFO: This is another message
tests/test_unity_core.c:106:testMessageShouldDisplayMessageWithoutEndingAndGoOnToPass:PASS
tests/test_unity_core.c:115:testMessageShouldDisplayMessageWithoutEndingAndGoOnToFail:INFO: This is yet another message
tests/test_unity_core.c:113:testMessageShouldDisplayMessageWithoutEndingAndGoOnToFail:PASS
tests/test_unity_core.c:122:testTrue:PASS
tests/test_unity_core.c:129:testFalse:PASS
tests/test_unity_core.c:136:testSingleStatement:PASS
tests/test_unity_core.c:149:testPreviousPass:PASS
tests/test_unity_core.c:154:testNotVanilla:PASS
tests/test_unity_core.c:161:testNotTrue:PASS
tests/test_unity_core.c:168:testNotFalse:PASS
tests/test_unity_core.c:175:testNotUnless:PASS
tests/test_unity_core.c:182:testNotNotEqual:PASS
tests/test_unity_core.c:189:testFail:PASS
tests/test_unity_core.c:196:testIsNull:PASS
tests/test_unity_core.c:205:testIsNullShouldFailIfNot:PASS
tests/test_unity_core.c:214:testNotNullShouldFailIfNULL:PASS
tests/test_unity_core.c:223:testIsEmpty:PASS
tests/test_unity_core.c:232:testIsEmptyShouldFailIfNot:PASS
tests/test_unity_core.c:241:testNotEmptyShouldFailIfEmpty:PASS
tests/test_unity_core.c:250:testIgnore:PASS
tests/test_unity_core.c:258:testIgnoreMessage:PASS
tests/test_unity_core.c:266:testProtection:PASS
tests/test_unity_core.c:287:testIgnoredAndThenFailInTearDown:IGNORE
: [[[[ Test Should Have Passed But Did Not ]]]]

tests/test_unity_core.c:320:testThatDetailsCanBeHandleOneDetail:PASS
tests/test_unity_core.c:333:testThatDetailsCanHandleTestFail:PASS
tests/test_unity_core.c:346:testThatDetailsCanBeHandleTwoDetails:PASS
tests/test_unity_core.c:359:testThatDetailsCanBeHandleSingleDetailClearingTwoDetails:PASS

-----------------------
30 Tests 1 Failures 1 Ignored 
FAIL
</pre>
</details>

Checking the source, I found out that [this line](https://github.com/ThrowTheSwitch/Unity/blob/386c540510929c0cf6f7b8d04cb4af40754bb822/test/tests/test_unity_core.c#L299) in "testFailureCountIncrementsAndIsReturnedAtEnd" causes the failure because of "Unity.CurrentTestFailed" which has been set to 1. My questions are,

- Is this failure intended?
- If so, what is the recommended way to run Unity's test?
- If not, why don't we save the result of "getFlushSpyCalls()" and check it after "UnityConcludeTest()"? (or otherwise, just erase [the line](Unity.CurrentTestFailed))

**Comment by mvandervoord** [comment]
Fixed.
