### ISSUE TITLE
Have an about/description section in the README

### ISSUE THREAD

**Issue by carsonalh** [ThrowTheSwitch/Unity#534]
The README has no explanation of what the repo even is in the first place, or how it should be compiled and run, which is confusing for newcomers (the people who actually need the README the most). This is, by any measure, a matter of opinion, but I think it would make it that little bit easier if this were added.

It should probably have:
 * an explanation of _what_ Unity even is (a testing framework ... );
 * what they, the user will need to compile it (CMake + GNU Make/Visual Studio);
 * maybe an explanation of _how_ to compile it (`cmake . -DCMAKE_INSTALL_PREFIX=<your install prefix>` etc. + how to compile with the extensions); and
 * what they will need to run it (an implementation <stdio.h>).

**Comment by mvandervoord** [comment]
@carsonalh This is an excellent idea and I will do so. Your examples prove why this would be useful, since most of the things you've identified as requirements are options (cmake, stdio.h, etc). 

Thanks for the great advice!
