### ISSUE TITLE
How to deal with avr-gcc `__flash` qualifier?

### ISSUE THREAD

**Issue by davidrea** [ThrowTheSwitch/Unity#566]
Hello! I'm curious if Unity has a preferred / proper method of handling special cross-compiler qualifiers not recognized by gcc on the development machine?

I'm trying to get a module for a bare-metal AVR (ATMega328p) project under test, but running into problems with the `__flash` qualifier, which [locates data in the .progmem.data section](https://gcc.gnu.org/onlinedocs/gcc/Named-Address-Spaces.html). 

Unity/CMock is trying to mock the `usart.h` file, which contains function signatures that look like this:

    void uart0_puts_p(const __flash char *string);

These result in typedefs and function prototypes in `mock_usart.h` file for mock-management that look like:

    void uart0_puts_p_CMockExpect(UNITY_LINE_TYPE cmock_line, const __flash char* string);
    typedef void (* CMOCK_uart0_puts_p_CALLBACK)(const __flash char* string, int cmock_num_calls);

gcc on my linux box gets wrapped 'round the axle on the `__flash` qualifier:

```
In file included from build/test/mocks/mock_usart.h:6,
                 from build/test/runners/test_stateMachine_interface_runner.c:6:
../lib/avr-uart-lib/usart.h:1596:28: warning: type defaults to ‘int’ in declaration of ‘__flash’ [-Wimplicit-int]
 1596 |    void uart0_puts_p(const __flash char *string); // send string from flash memory
      |                            ^~~~~~~
../lib/avr-uart-lib/usart.h:1596:36: error: expected ‘;’, ‘,’ or ‘)’ before ‘char’
 1596 |    void uart0_puts_p(const __flash char *string); // send string from flash memory
      |                                    ^~~~
```

Is there a setting in `project.yml` I can use to remove these qualifiers, instruct CMock to remove them, or instruct gcc on the host PC on how to deal with them?

**Comment by davidrea** [comment]
For now, at least, I've found an effective workaround is to just use the preprocessor to remove the `__flash` qualifiers. Add to project.yml:

```yml
:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :common: &common_defines []
  :test:
    - *common_defines
    - TEST
    - __AVR_ATmega328P__
    - F_CPU=16000000UL
    - __flash=              <<<<< add this <<<<<
  :test_preprocess:
    - *common_defines
    - TEST
```

**Comment by mvandervoord** [comment]
Another option is to add __flash to the stripables list in your cmock configuration.
