### ISSUE TITLE
UNITY_INT_WIDTH issue in unity_internals.h

### ISSUE THREAD

**Issue by SJacquart** [ThrowTheSwitch/Unity#572]
Hello

I am using Ceedling :ceedling_version: 0.31.1 installed directly from Ruby gem.

While trying to configure Unity to run like a TI-compiler (16bits for both Uint16 and Uint8) I found an issue related with UNITY_INT_WIDTH=16 define that I added in my ceedling configuration.
After setting it I was still having issues on array content comparison and dug into the core files of Unity.

The content of the unity_internals.h files state the following: 
```
#if (UNITY_INT_WIDTH == 32)
    typedef unsigned short  UNITY_UINT16;
#elif (UNITY_INT_WIDTH == 16)
    typedef unsigned int    UNITY_UINT16;
#else
```
It should be the other way round... 

Simple test to expose the issue:
```
void test_compiler_compatibility(void)
{
    Uint16 txQueue[20];
    Uint16 piBuf[20];
    Uint16 i;
    Uint16 iSize = 3u; // leave the rest unassigned on purpose
    piBuf[0] = 0x6B;piBuf[1] = 1; piBuf[2] = 1;
    for (i = 0u; i < iSize; i++)
    {
        txQueue[i] = piBuf[i];
    }
    printf("maccros extended sizeof(UNITY_INT16) %i with signed short %i and signed int %i\n",
           sizeof(UNITY_INT16), sizeof(signed short),sizeof(signed int));
    printf("UNITY_INT_WIDTH: %i\n",UNITY_INT_WIDTH);
    TEST_ASSERT_EQUAL_UINT16_ARRAY_MESSAGE(&(piBuf[0]), &(txQueue16[0]),3u,"issue on array index handle");
}
```

**Comment by mvandervoord** [comment]
The `UNITY_INT_WIDTH` macros seem correct. If an `int` is 32-bits, you'll likely need a `short` to get a 16bit number. If the integer width is 16 bits, you can use a full int to get a 16-bit int. 

What output are you getting when you run this test?

Are you running your tests on a TI simulator are target hardware?

**Comment by SJacquart** [comment]
I am running the test with default gcc for now. It seems that TI stopped supporting its simulators (reason is they claim evaluation boards are cheap ... but this won't work with unit testing... !). 

Anyway, your answer seems perfectly logical. 
With this configuration - UNITY_INT_WIDTH=16 and the unity package as installed I get the following outputs & error :
`"maccros extended sizeof(UNITY_INT16) 4 with signed short 2 and signed int 4"
FAILED TEST SUMMARY : Element 2 Expected 1983344533 Was 1983491329` 
I am probably reaching uninitialized memory area which would indicate that the pointers are not incremented by 16bits.

I assumed the UNITY_INT_WIDTH would impact gcc but it seems it's only setting the maccros for Unity, am I right ? then it is simply missing a proper compilation option first.

**Comment by mvandervoord** [comment]
Ah. The problem is that you're setting UNITY_INT_WIDTH to 16, but you're not actually on a 16-bit compiler. You're likely on a 64 bit compiler (gcc running natively). 

In the case where you're running tests on a different platform than you're running your release code, it's usually best to not specify the int width and let Unity discover it on its own. It's usually correct. In the event that this doesn't work, you can specify the int size of the platform you're running your tests.

**Comment by SJacquart** [comment]
Yes, indeed. I applied only partially a guideline on adapting Unity to embedded target... and ended up mixing everything. 
Thank you for your help.
