### ISSUE TITLE
Want TEST_ASSERT_DOUBLE/FLOAT_ARRAY_WITHIN?

### ISSUE THREAD

**Issue by fhchl** [ThrowTheSwitch/Unity#574]
Is there any special reason, why a macro for float or double comparison a la 

    TEST_ASSERT_DOUBLE_ARRAY_WITHIN(delta, expected, actual, num)

is not implemented, while it is for all the other types? If not, I wouldn't mind working on a PR for the above (+floats).

**Comment by AJIOB** [comment]
Looks like it was implemented in PR #644

**Comment by fhchl** [comment]
Awesome, closing issue.
