### ISSUE TITLE
Meinderscominc@gmail.com

### ISSUE THREAD

**Issue by meinderscominc** [ThrowTheSwitch/Unity#577]
__Originally posted by @meinderscominc in https://github.com/ThrowTheSwitch/Unity/issues/576__

**Comment by meinderscominc** [comment]
Cleanse the dev community

**Comment by JuPrgn** [comment]
Mark I think you can blacklist a user on your repository setting

**Comment by mvandervoord** [comment]
Thanks, @JuPrgn -- I believe I have done so.
