### ISSUE TITLE
Undefined References in Libc.a When Linking

### ISSUE THREAD

**Issue by samc1213** [ThrowTheSwitch/Unity#593]
I am using Unity on my local Windows machine with GCC without issue. However, when I use a custom compiler/linker for my target hardware, I get an issue with undefined references. This issue happens once I link against a `unity.o` object file. Removing this file from the linking step allows me to compile correctly.

```
C:/openecu/platform/2_9_0_r2020-1/tools/gcc_4_7_3/ppc/bin/../powerpc-eabispe/lib\libc.a(lib_a-sbrkr.o): In function `_sbrk_r':
sbrkr.c:(.text+0x74): undefined reference to `sbrk'
C:/openecu/platform/2_9_0_r2020-1/tools/gcc_4_7_3/ppc/bin/../powerpc-eabispe/lib\libc.a(lib_a-writer.o): In function `_write_r':
writer.c:(.text+0x7c): undefined reference to `write'
C:/openecu/platform/2_9_0_r2020-1/tools/gcc_4_7_3/ppc/bin/../powerpc-eabispe/lib\libc.a(lib_a-closer.o): In function `_close_r':
closer.c:(.text+0x74): undefined reference to `close'
C:/openecu/platform/2_9_0_r2020-1/tools/gcc_4_7_3/ppc/bin/../powerpc-eabispe/lib\libc.a(lib_a-fstatr.o): In function `_fstat_r':
fstatr.c:(.text+0x78): undefined reference to `fstat'
C:/openecu/platform/2_9_0_r2020-1/tools/gcc_4_7_3/ppc/bin/../powerpc-eabispe/lib\libc.a(lib_a-isattyr.o): In function `_isatty_r':
isattyr.c:(.text+0x74): undefined reference to `isatty'
C:/openecu/platform/2_9_0_r2020-1/tools/gcc_4_7_3/ppc/bin/../powerpc-eabispe/lib\libc.a(lib_a-lseekr.o): In function `_lseek_r':
lseekr.c:(.text+0x7c): undefined reference to `lseek'
C:/openecu/platform/2_9_0_r2020-1/tools/gcc_4_7_3/ppc/bin/../powerpc-eabispe/lib\libc.a(lib_a-readr.o): In function `_read_r':
readr.c:(.text+0x7c): undefined reference to `read'
```
Can someone please help me with these issues? I don't see what in unity would cause this.

**Comment by Letme** [comment]
Do you recompile the `unity.o` with target hardware custom compiler? Maybe you have few too many flags that are not applicable for target hardware but work just fine on host PC (from errors I would assume target hardware has no filesystem predicted in libc, so you probably need to drop some defines)?

**Comment by samc1213** [comment]
Yes I am compiling `unity.o` from `unity.c` by using the custom compiler. The target hardware does not have a filesystem. What defines to drop might you be referring to?

**Comment by Letme** [comment]
You didn't say much about your build system, but the error does not seem to be connected to unity itself, but to the way your runners are created (test case and its execution). Those seem to somehow require or expect to have filesystem capabilities (which your local Windows has). Hence, I mentioned that maybe you are missing some defines somewhere to remove this capability or define printing of results somehow (for example here is closest connection to libc capabilities - but no filesystem stuff https://github.com/ThrowTheSwitch/Unity/blob/master/src/unity_internals.h#L275-L300). I am pullzed why removing unity.o would complete linking as that somehow indicates that you are not using unity.o on target hardware (as include should be there for runner). Keep in mind that Unity expects some `putchar` capabilities which can also be mapped to filesystem file write (`/dev/stdout` is a file in Linux).

**Comment by samc1213** [comment]
Thanks for pointing me to `putchar`! I just created a `unity_config.h` file, with the below contents (for now - eventually I'd like to print test output over serial from the embedded device)

```
#ifndef RMU_UNITY_CONFIG
#define RMU_UNITY_CONFIG

#define UNITY_OUTPUT_CHAR(a)
#define UNITY_OUTPUT_FLUSH()
#define UNITY_OUTPUT_START()
#define UNITY_OUTPUT_COMPLETE()

#endif
```

And then I compiled with `-DUNITY_INCLUDE_CONFIG_H`, and it built just fine. Thank you for your help :)
