### ISSUE TITLE
Test summary prints gibberish on AVR

### ISSUE THREAD

**Issue by rstanchak** [ThrowTheSwitch/Unity#606]
Expected output:
```
-----------------------
1 Tests 1 Failures 0 Ignored
FAIL
```

Actual output:
```
11\x4ALMNOPQRS0\x57YZ[\]^_`abcdefghij`
```

This seems to be due to incorrect loading of strings from program memory on AVR.  The solutions proposed in https://github.com/ThrowTheSwitch/Unity/pull/482 produce the expected output.

**Comment by ivankravets** [comment]
See PR https://github.com/ThrowTheSwitch/Unity/pull/607
