### ISSUE TITLE
test pass when expected function not called

### ISSUE THREAD

**Issue by DanieleNardi** [ThrowTheSwitch/Unity#617]
Let's suppose I have a unit test like the following one:
```
void test_calledFunction()
{
    ...
    foo_Expected();
    bar_Expected();
    res = myFunc();
    TEST_ASSERT_EQUAL(0,res);
}
```
and the function to test like 
```
uint8_t myFunc()
{
    ...
    foo();
    ...
    return 0;
}
```

Why does the unit test is passed even if the function bar() is not called?

**Comment by DanieleNardi** [comment]
The problem is the runner generator doesn't fullfill the followinf functions:
```
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}
```
This is how I call the ruby scripts:
```
ruby /opt/cmock/lib/cmock.rb foo.h -ocmockConfig_1.yml &>/dev/null
ruby /opt/cmock/lib/cmock.rb   bar.h -ocmockConfig_2.yml &>/dev/null
mkdir -p runners &> /dev/null
ruby /opt/Unity/auto/generate_test_runner.rb myUnitTestSource.c runners/AdcLibraUnitTest_Runner.c &> /dev/null
```

**Comment by DanieleNardi** [comment]
Found the issue!
The mocks header file shall be included with " " instead of < > in your unit test source file.

Is this a bug or a work-as-expected?

**Comment by mvandervoord** [comment]
Yes, this is expected. Mocks are never in your system directories, so we always use "" instead of <>

**Comment by DanieleNardi** [comment]
Thank you!
