### ISSUE TITLE
The makefile error is equal to the number of unit test results failures

### ISSUE THREAD

**Issue by smallflypiglq** [ThrowTheSwitch/Unity#626]
./qu
qu_ut.c:15:test_qu_float_process_1:PASS
qu_ut.c:33:test_qu_float_process_2:FAIL: Expected 0 Was -1
qu_ut.c:44:test_qu_float_process_3:FAIL: Expected 0 Was 1
qu_ut.c:49:test_qu_float_process_4:IGNORE
qu_ut.c:57:test_add:FAIL: Expected 3 Was 0

-----------------------
5 Tests 3 Failures 1 Ignored 
FAIL

make: *** [Makefile:79: run] Error 3

./qu
qu_ut.c:15:test_qu_float_process_1:PASS
qu_ut.c:33:test_qu_float_process_2:FAIL: Expected 0 Was -1
qu_ut.c:49:test_qu_float_process_4:IGNORE
qu_ut.c:57:test_add:FAIL: Expected 3 Was 0

-----------------------
4 Tests 2 Failures 1 Ignored 
FAIL

make: *** [Makefile:79: run] Error 2

**Comment by Letme** [comment]
Is there a point/question with this?

**Comment by smallflypiglq** [comment]
I run the program in Makefile, Makefile will fail, and the return value of failure is equal to the failure of the unit test.now I take the program execution from Makefile, and it runs normally.But I want to know that this phenomenon is normal?

**Comment by Letme** [comment]
What do you mean runs normally? Do you mean that `.out` (or `.exe`) binary of Runner returns 0, when executed standalone, although there are test failures? Did you confirm that with the `echo $?` for example? Makefile you took from where?

**Comment by smallflypiglq** [comment]
Thank you very much for your answer. The return result of the direct execution is also the number of Failures number. I know the reason, because the return value of UnityEnd is the number of cell test errors, so when performing the program in Makefile, the program execution fails.
