### ISSUE TITLE
Add TEST_ASSERT_WITHIN_DOUBLE_ARRAY

### ISSUE THREAD

**Issue by jonathon-generac** [ThrowTheSwitch/Unity#630]
Currently unity supports, `TEST_ASSERT_EQUAL_DOUBLE_ARRAY`.  In most cases, it's not helpful to do equality checks on floating point numbers, since a very small rounding error could result in a failed test.  It would be much more helpful to implement `TEST_ASSERT_EQUAL_DOUBLE_ARRAY`, which would allow the check to be done within a certain range of the expected value or even, better yet, to have a way to do the check within a certain percentage of the expected value.  Please consider adding this as a feature for double-precision and/or single-precision values.

**Comment by mvandervoord** [comment]
Completed.
