### ISSUE TITLE
How do I use Unity and C# / C / C++ on chromebook?

### ISSUE THREAD

**Issue by TheRealDigitalMaster** [ThrowTheSwitch/Unity#636]
When I downloaded this on my chromebook, it doesn't work. Only the .html files work. Is there a way to use this without extension?

**Comment by Letme** [comment]
What mean "it doesn't work". What extension are you looking at?

**Comment by TheRealDigitalMaster** [comment]
I am not looking for extensions, I am just looking to see if I should open in localhost, or I should get a new device.

**Comment by TheRealDigitalMaster** [comment]
And it says this:
![Screenshot 2022-10-30 09 34 03](https://user-images.githubusercontent.com/112659665/198891062-3897f169-fbe7-4305-9f9d-73e4f1264cfc.png)
So should I upload to localhost?

**Comment by mvandervoord** [comment]
I believe you have this project (Unity Test) confused with Unity 3d, the
graphic engine. :)

**Comment by TheRealDigitalMaster** [comment]
Yes, but to run Unity 3d, it has to support Unity Test coding languages (C / C# / C++)

**Comment by TheRealDigitalMaster** [comment]
But it doesn't work in HTML files. So should I upload to localhost?

**Comment by mvandervoord** [comment]
I'm not sure how the installation for Unity 3d works. I can assure you,
though, that there is no interdependencies between these unrelated
projects. It's just a coincidence that they share a name.

**Comment by TheRealDigitalMaster** [comment]
Ok. I just figured out how to import Unity WebGL in my websites. Thanks!
