### ISSUE TITLE
Running unity on a microcontroller

### ISSUE THREAD

**Issue by AshrafMasoud5** [ThrowTheSwitch/Unity#637]
why can't Unity Run on a microcontroller by adding a porting file to log the output of the test cases to a computer?

It would be much more convenient than mocking 80% of every embedded project.

I don't know the framework source code, but I would like to help adding such a feature.

**Comment by Letme** [comment]
It can run, and it is running, but you will still need to mock 80% of code space as you want control (determinism) over peripherals and their outputs.

You just cross compile the runner and then flash it over debugger (or some other protocol if you have bootloader) and get printf output back for parsing. Ceedling can do this whole chain out of the box.

**Comment by mvandervoord** [comment]
Hi @AshrafMasoud5. As @Letme said, this is already possible and people use it this way all the time. However, you will never get as good of tests running it on the micro. I'd like to refer you to this article which sums it up fairly well: http://www.throwtheswitch.org/build/which
