### ISSUE TITLE
mock function?

### ISSUE THREAD

**Issue by MJ-CJM** [ThrowTheSwitch/Unity#638]
Hello, may I ask if there is a mock function in this project, just like fake function call returns;

**Comment by mvandervoord** [comment]
Hi. I'd like to refer you to [throwtheswitch.org ](https://throwtheswitch.org). This site covers all the tools that work with Unity, including CMock for creating mocks, and Ceedling for managing test builds.

**Comment by MJ-CJM** [comment]
Thank you very much, I will see and use it truthfully.
