### ISSUE TITLE
Passing safe_level with the 2nd argument of ERB.new is deprecated

### ISSUE THREAD

**Issue by rhobison** [ThrowTheSwitch/Unity#649]
I am getting this warning when trying to generate test runners:

```
...unity-src/auto/generate_test_runner.rb:344: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
```

Ruby version:
```
ruby --version
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x64-mingw-ucrt]
```

Is there a plan to update `generate_test_runner.rb` and get rid of the deprecated function/usage?

**Comment by rhobison** [comment]
Hi @lukzeg,
That is great!
Yes, we can close it. Thanks a lot.

In our test system, we are using the tag v2.5.2 (latest). Do you know when a new version will be released?

Thank you!

**Comment by lukzeg** [comment]
Hi @rhobison ,

Unfortunately I'm not the one who can say this. 

@mvandervoord are you considering to create new release in in near future?

**Comment by mvandervoord** [comment]
:) Yes. I wish I was better at putting a timeline on things, but there are a few loose ends I wanted to wrap up before releasing the next version.
