### ISSUE TITLE
Question: How to hide successful tests (passed tests)?

### ISSUE THREAD

**Issue by miguno** [ThrowTheSwitch/Unity#652]
Is there a configuration option to hide successful tests and only show failed tests, if any?

Going from this:

```
.../build/test/Debug/unity_testsuite
.../test/unity_tests.c:45:string_equality:PASS
.../test/unity_tests.c:46:pointer_equality:PASS
.../test/unity_tests.c:47:verify_sum:PASS

-----------------------
3 Tests 0 Failures 0 Ignored
OK
```

to sth like:

```
.../build/test/Debug/unity_testsuite
-----------------------
3 Tests 0 Failures 0 Ignored
OK
```

I know how to write tooling around the output if need be, but am looking for a configuration approach.

**Comment by mvandervoord** [comment]
There are a variety of scripts in the auto directory for formatting the output with different styles. All of them are post-processors. Unity always outputs verbose output and relies on the surrounding build system to beautify it.

**Comment by miguno** [comment]
Ok, thanks for the quick feedback @mvandervoord !
