### ISSUE TITLE
Defining setUp() in common file other than test file leads to multiple definition of `setUp'

### ISSUE THREAD

**Issue by lifang-zhang** [ThrowTheSwitch/Unity#678]
In the case where different test files (e.g. test file 1, test file 2, ... test file N) share the same `setUp()` function, it makes sense to define `setUp()` in another common file (e.g. common.c), but then there is multiple definition of `setUp()` compiling error if generate_test_runner.rb is used to generate runner file. 

The problem comes from that in generate_test_runner.rb, it first sets `:has_setup` to true if the `:setup_name` is not empty with `@options[:has_setup] = !options[:setup_name].nil?`. The `:setup_name`  by default is `setUp` unless it is overridden with yml configuration file or with command line option `--setup_name=`, so the `:has_setup` is by default true, but it then scans the test file and see if `setUp()` is defined there in function `find_setup_and_teardown`, if there is no definition for `setUP()` , `:has_setup`  will be overridden to false, in which case an empty `setUp()` is defined. If `setUp`  is defined in another common file, this will leads to multiple definition of `setUp` error.

I understand that defining an empty `setUp()` in generate_test_runner.rb is to make sure that `setUp()` is always defined. But should there be a mechanism to override this behavior, so applications can tell that `setUp()` is defined somewhere else instead of in the test file, for example through configuration or whatever better way?

As a solution, of course users can just comment out following line of code
```
@options[:has_setup] = source =~ /void\s+#{@options[:setup_name]}\s*\(/
```

But it makes more sense to give users options than modifying the source code, it would be much easier to update Unity later on.

**Comment by mvandervoord** [comment]
I don't think we're going to do this one. It's an incredibly rare situation where multiple modules share the same setUp. Of those situations, it's even rarer that they'd be long enough to be concerned with duplicating. For situations where this is true, just name the helper function something custom like `sharedSetup` and have your `setUp` function in each class just call that. Adding another layer of settings to cover this usecase isn't worth the complexity.
