### ISSUE TITLE
cmake and unity_config.h

### ISSUE THREAD

**Issue by guntern** [ThrowTheSwitch/Unity#688]
Hi,
I am currently switching a makefile-project to cmake. But I am struggling with unity. I need to set UNITY__INCLUDE_CONFIG_H in order to activate doubles. For this I need to make my own unity_config.h available, when compiling unity. But I have not figured out a way to provide the include directory containing my unity_config.h, when building unity with cmake.

My project structure is as follows (simplified):
```
project
  |-- src
  |-- testing
           |-- unity
           |        |-- the unity repo stuff
           |-- CMakeLists.txt
           |-- unity_config.h
           |-- test.c
```

In the CMakeLists.txt shown in the structure above I try:
```cmake
add_subdirectory(unity)
target_compile_option(unity PUBLIC -DUNITY_INCLUDE_CONFIG_H)
target_include_directories(unity PUBLIC ${CMAKE_CURRENT_LIST_DIR})
```

The compile options get set. I know that, because when the `target_include_directories` line is not present, the compiler complains, that he cannot find `unity_config.h`, which means I found a configuration, which actually makes him look for it.

The `target_include_directories` however fails during cmake configuration with
```
[cmake] CMake Error in testing/unity/CMakeLists.txt:
[cmake]   Target "unity" INTERFACE_INCLUDE_DIRECTORIES property contains path:
[cmake] 
[cmake]     "C:/Users/projectpath/testing/"
[cmake] 
[cmake]   which is prefixed in the source directory.
```

The solution provided [here](https://stackoverflow.com/questions/25676277/cmake-target-include-directories-prints-an-error-when-i-try-to-add-the-source) does not work in my point of view, because I would need to include unity_config.h during compilation. Or am I missing something?

How can I combine cmake compilation with my own unity_config.h?

Alternatively I probably could specify the defines from unity_config.h in the target_compile_options directly. But is this the preferred way?

Thanks in advance.

**Comment by ramadhanafif** [comment]
Could this is caused by the out-of-tree file? The unity_config.h exist on a higher directory level than unity's CMakeLists.txt

**Comment by guntern** [comment]
> Could this is caused by the out-of-tree file? The unity_config.h exist on a higher directory level than unity's CMakeLists.txt

I think this could be related. But in my point of view, it has to be this way, because I cannot move unity_config.h inside the unity directory, because it is specific to my project and thus should be versioned along with my project.

**Comment by mvandervoord** [comment]
Does CMake not allow you to set defines as compiler flags?

**Comment by AndersonMartins1** [comment]
Para resolver o problema de integrar o unity_config.h personalizado ao compilar o Unity usando CMake, aqui estão algumas sugestões:

Especificar as definições diretamente como opções de compilação:

Ao invés de tentar incluir o diretório que contém o unity_config.h, você pode especificar as definições diretamente como opções de compilação.
Isso pode ser feito usando target_compile_definitions no seu arquivo CMakeLists.txt.
Por exemplo:

target_compile_definitions(unity PUBLIC UNITY_INCLUDE_CONFIG_H)


Manter o unity_config.h no mesmo diretório do CMakeLists.txt do Unity:

Uma abordagem alternativa é manter o unity_config.h no mesmo diretório do CMakeLists.txt do Unity.
Dessa forma, você pode incluir diretamente o unity_config.h usando target_include_directories.
Certifique-se de manter o unity_config.h versionado junto com seu projeto, conforme você mencionou.
Verificar se há problemas com caminhos relativos:

Certifique-se de que os caminhos para o unity_config.h estão corretamente especificados em relação ao diretório do seu projeto.
Verifique se não há problemas com caminhos absolutos que possam estar causando conflitos.
Ao seguir essas sugestões, você deve conseguir integrar com sucesso o unity_config.h personalizado ao compilar o Unity usando CMake. Se houver alguma dúvida ou problema específico, não hesite em perguntar na comunidade ou entrar em contato com os mantenedores do Unity.

**Comment by guntern** [comment]
> Does CMake not allow you to set defines as compiler flags?

This could be an alternative. But I was trying to go the way intended by unity, which I like because of the documentation in the unity_config.h. But maybe one could copy this into a CMakeLists.txt.

@AndersonMartins1 : After translating your comment to English, I am still a bit confused. The first option is, what I used to activate the inclusion of the config file in the first place. And as stated above, I could use it to specifiy the other settings as well. 

Putting my unity_config.h alongside the CMakeLists.txt of unity not sensible in my point of view. The unity directory is integrated as git submodule. And thus, if adding my personal unity_config.h I would mess with the submodule and would not be able to have it in the version control of my project. Or am I overlooking something there?

Checking the paths is a good advice. I will go over them once more.

**Comment by AndersonMartins1** [comment]
I see, it looks like you're trying to figure out how to integrate the Unity_config.h file into your project using CMakeLists.txt, right? Here is a suggestion on how to do this:

Keep Unity_config.h where it is:
Let's keep Unity_config.h where it is, in the Unity submodule directory. This way, we don't touch the version control of your main project.

See Unity_config.h in your CMakeLists.txt:
In your main CMakeLists.txt file, we can add the path to Unity_config.h as an include option for the compiler. Here is an example of how to do this:

# Define a variable with the path to Unity_config.h
set(UNITY_CONFIG_PATH ${CMAKE_CURRENT_SOURCE_DIR}/path/to/Unity/Unity_config.h)

# Add the Unity submodule directory to the include path
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/path/to/Unity)

# Add the path to Unity_config.h as an include option
add_definitions(-include ${UNITY_CONFIG_PATH})

Remember to replace path/to/Unity with the actual path to the Unity submodule directory in your project.

With this approach, you will be able to use Unity_config.h in your project without messing up Unity submodule versioning.


I don't know if you've tried this? Could you explain better and give more details. Maybe someone knows how to solve it, sometimes even if you do everything right, a small detail complicates everything

**Comment by AndersonMartins1** [comment]
ou uma alternativa seria especificar diretamente as opções de compilação, incluindo o Unity_config.h durante a compilação.

Aqui está uma sugestão de como fazer isso usando target_compile_options: add_subdirectory(unity)
target_compile_options(unity PUBLIC -DUNITY_INCLUDE_CONFIG_H)
target_compile_options(unity PUBLIC -I${CMAKE_CURRENT_LIST_DIR})

Dessa forma, você está definindo as opções de compilação -DUNITY_INCLUDE_CONFIG_H para incluir o Unity_config.h e -I${CMAKE_CURRENT_LIST_DIR} para incluir o diretório atual (onde seu Unity_config.h está localizado).

Essa abordagem deve resolver o problema e permitir que você compile o Unity com seu próprio Unity_config.h usando CMake.

**Comment by AndersonMartins1** [comment]
If nothing works, turn the machine on and off.

**Comment by guntern** [comment]
Hi @AndersonMartins1,
it seems I got it working. I had to dig up my project related to this issue.

# Workaround

Indeed the workaround for the time being was

```cmake
target_compile_options(unity PUBLIC
    -DUNITY_INCLUDE_DOUBLE
    -DUNITY_OUTPUT_COLOR
)
```

One could consider this also a solution, though, as pointed out above, e.g. by @mvandervoord.

# Solution

Which variants did work for me with my own `unity_config.h` replacing the above target compile options.

## Solution1

```cmake
include_directories(${CMAKE_CURRENT_LIST_DIR})
add_subdirectory(unity)
target_compile_options(unity PUBLIC -DUNITY_INCLUDE_CONFIG_H)
```

So using `include_directories` instead of `target_include_directories` worked. It must be present before the `add_subdirectory`, so that indeed it gets added to the include directories of unity.

## Solution2

```cmake
add_subdirectory(unity)
target_compile_options(unity PUBLIC -DUNITY_INCLUDE_CONFIG_H)
target_compile_options(unity PUBLIC -I${CMAKE_CURRENT_LIST_DIR})
```

This also worked. Surprisingly adding the include directory to the target as a compile option does not trigger the cmake error "in my original post"

# Final Thought

The mixture of Portuguese and English and the way the answers are written got me wondering, whether I was served with ChatGPT responses. Also looking at the expertise of @AndersonMartins1 does not seem to be related to unity as the testing framework but rather the unity-engine, which also gets me wondering. Nevertheless, I got a solution to my problem so I am happy anyway.

**Comment by AndersonMartins1** [comment]
I'm glad you managed to solve it because sometimes it's frustrating you have everything written down correctly but it doesn't work

**Comment by AndersonMartins1** [comment]
Creating games in Unity, whether in 2D or 3D, always comes with those annoying little problems that appear out of nowhere, right? It's like, you're there all excited, placing your characters, creating this incredible setting, and suddenly, bam, something doesn't work as expected. It could be a crazy bug in the code, or maybe the game's physics aren't behaving as they should, or even the game's performance is leaving something to be desired. But it's part of it, it's normal! The important thing is not to despair. With a little patience and a dose of trial and error, we always end up finding a solution. And the cool thing is that there is a lot of help available out there, like forums, tutorials and even videos on YouTube. So, if you have a problem, go find a solution and continue playing that game.

**Comment by guntern** [comment]
> Creating games in Unity, whether in 2D or 3D, always comes with those annoying little problems that appear out of nowhere, right? It's like, you're there all excited, placing your characters, creating this incredible setting, and suddenly, bam, something doesn't work as expected. It could be a crazy bug in the code, or maybe the game's physics aren't behaving as they should, or even the game's performance is leaving something to be desired. But it's part of it, it's normal! The important thing is not to despair. With a little patience and a dose of trial and error, we always end up finding a solution. And the cool thing is that there is a lot of help available out there, like forums, tutorials and even videos on YouTube. So, if you have a problem, go find a solution and continue playing that game.

@AndersonMartins1 are you aware that this repository is **not** related to the Unity game engine? It is related to a unittesting framework (https://www.throwtheswitch.org/unity). In my opinion it is a very confusing name clash, because it is hard to find information about the unittesting framework because the whole internet is covered up with the game engine.

**Comment by AndersonMartins1** [comment]
Living and learning this I didn't know, as I'm new I'm trying to get used to it, but there are so many details and functions, I'll try to remember because it's really easy to get confused

**Comment by AndersonMartins1** [comment]
I opened the website, thanks for the tip, this website link is worth gold
