### ISSUE TITLE
Release for floats and doubles testing

### ISSUE THREAD

**Issue by atticusrussell** [ThrowTheSwitch/Unity#696]
I would like the current version to be a release in order to use it correctly with PlatformIO . The last release, [v2.5.2](https://github.com/ThrowTheSwitch/Unity/releases/tag/v2.5.2), does not have support for float and double comparison such as TEST_ASSERT_GREATER_THAN_DOUBLE.

The reason I would like this in a new release is that I am running into issues with PlatformIO where the registry only has v2.5.2 from two years ago with slight customization that handle unity_config.h for PlatformIO, and when I manually include the last commit from this repo instead of the PlatformIO registry using lib_deps, it is missing that customization and has errors.

A new release would be included in the PlatformIO registry, and eliminate my need for goofy workarounds.

**Comment by mvandervoord** [comment]
It's in the works. :)

**Comment by mvandervoord** [comment]
Complete
