### ISSUE TITLE
Template-based runner generation

### ISSUE THREAD

**Issue by damphyr** [ThrowTheSwitch/Unity#70]
The runner generation script creates the runner's C code with various puts statements.

I've had to adapt the runner in several projects i.e. to allow  coverage measurement retrieval in embedded devices etc. and I have also had to hand over maintenance to people with little knowledge of Ruby.

In both cases using a template for the runner code has proven a much more effective alternative. To this effect I've written a runner generator that uses an ERB template.

The whole thing is up on [damphyr/bare_unity](https://github.com/damphyr/bare_unity).

It's stripped down to only what I have been using (so no plugins or ordered execution etc.)

It also is significantly less Ruby code than the original runner (but that's also due to the omission of some features). It should be easy to add the missing functionality in case you are interested

**Comment by mvandervoord** [comment]
As much as I love the idea of this (and I do), the Unity support scripts have been heading in the direction of more complex over time as they take on more features. They lend themselves even less well now to a template-based approach. I'm going to close this item for now, with the idea that we're still going to be putting in effort to make non-Ruby people happy!
