### ISSUE TITLE
static variable inside of target function is reset everytime when it is invoked

### ISSUE THREAD

**Issue by joe-ju** [ThrowTheSwitch/Unity#702]
Hi,
I implemented a test function in unity like:
/* tests */
void test_helloworld(void)
{
    target_fun();
    target_fun();
}

And the target function implementation in my source is the following:
void target_func(void)
{
    static in i = 0;
    if (++i >=2)
        printf("hello world\n");
}

The print never happened and after some investigation, when  target_fun() is invoked for the second time the "i" was reset to 0 again, but I also tested target_func(void) in the same way without unity and it worked. Do you have any idea about this test in unity? Thanks!

**Comment by mvandervoord** [comment]
I'm confident you've misdiagnosed what is happening here. Likely you've just missed a detail somewhere. Is it actually this example or is this a simplified version of the problem? If the latter, some things to double check:

* perhaps it's not actually marked `static`?
* perhaps there's an off-by-one error and you're calling the function 1 too-few many times?
* perhaps printf is getting eaten up somewhere in the process... try changing the print to something that sets a flag or something to verify?

Unity does a lot of tricky stuff in the background, but it can't change the rules of C for you. If you've marked a variable as static in your release function, it's still static and Unity can't touch it.

**Comment by joe-ju** [comment]
Hi, thanks.
My bad. I added the compilation macro "-Dstatic=" in my makefile, which means all static would be replaced with null.

Thanks a lot again!!

**Comment by mvandervoord** [comment]
:) Awesome. That makes sense!
