### ISSUE TITLE
#529 still unfixed after merge

### ISSUE THREAD

**Issue by paulcdca** [ThrowTheSwitch/Unity#718]
The merge that was meant to fix this issue only moved the problem.
During the call to UnityConcludeTest at line 300 in test_unity_core.c, UNITY_FLUSH_CALL is called.
UNITY_FLUSH_CALL is defined to UNITY_OUTPUT_FLUSH
UNITY_OUTPUT_FLUSH is defined to flushSpy by the makefile at line 22
flushSpy increments flushSpyCalls from 0 to 1

As the count of flushSpyCalls is being captured after the call to UnityConcludeTest, the assert against 0 fails.

**Comment by mvandervoord** [comment]
Can you double-check the cutting edge? I believe it's fixed now?

**Comment by paulcdca** [comment]
Yep, is fixed :)
Needed to disable -Weverything in the Makefile to get it to build, but thats a new issue that I'm sure you found via CI already
