### ISSUE TITLE
XML/JSON based report generating?

### ISSUE THREAD

**Issue by liyafe1997** [ThrowTheSwitch/Unity#730]
Seems unity now only supports output the result directly to the console.

It is better to have some xml-based report support. So it is able to integrate with some CI/CD platform, like Azure Pipeline.

`testResultsFormat: 'JUnit' # 'JUnit' | 'NUnit' | 'VSTest' | 'XUnit' | 'CTest'. Alias: testRunner. Required. Test result format. Default: JUnit.`

By the way, is there any tool can convert unity's console output result to one of the above report format?

**Comment by mvandervoord** [comment]
Hi.

Unity outputs a single format and then relies on output parsers to format it to whatever format you'd like. When using Ceedling, you can enable any of the report plugins to do this. When using Unity directly, there are output formatting scripts in the `auto` directory in Python and Ruby.

**Comment by liyafe1997** [comment]
> Hi.
> 
> Unity outputs a single format and then relies on output parsers to format it to whatever format you'd like. When using Ceedling, you can enable any of the report plugins to do this. When using Unity directly, there are output formatting scripts in the `auto` directory in Python and Ruby.

Found it! Thanks a lot!
